### ISSUE TITLE
Unable to get color images using ImageFormatConverter

### ISSUE THREAD

**Issue by rezaxdi** [basler/pypylon#1]
hi there,

I'm unable to run ImageFormatConverter on GrabResult : 

`NotImplementedError: Wrong number or type of arguments for overloaded function 'ImageFormatConverter_Convert'.
  Possible C/C++ prototypes are:
    Pylon::CImageFormatConverter::Convert(Pylon::IReusableImage &,Pylon::IImage const &)
    Pylon::CImageFormatConverter::Convert(Pylon::IReusableImage &,Pylon::CGrabResultPtr const &)
`

Is this function still incomplete ?

**Comment by basler-oss** [comment]
Hi rezaxdi,

After looking into the source code I would actually expect that this function is implemented. Could you send me a copy of you code sample which triggers this issue? Thanks!

**Comment by stefanklug** [comment]
@dmirecki We are working on a fix. The updates will be pushed in a few days.

**Comment by LucasVandroux** [comment]
I just started to use pypylon and I am looking forward to be able to use the ImageFormatConverter.

**Comment by stefanklug** [comment]
@dmirecki  I just pushed new changes to master. The ImageFormat converter should work now.
