### ISSUE TITLE
RetrieveResult,( timeoutMs=inf) Code Syntax

### ISSUE THREAD

**Issue by Acam8** [basler/pypylon#101]
Hello,

Looking inside the Programmers Guide, where the function RetrieveResult is described, it said that it is posible to set an infinity value to the timeout parameter.
But I'm getting an error, it's only possible to pass the argumetns as an unsigned int
How can I pass an infinity value as an argument to the RetrieveResult function in my python code?What is the  code syntax?

> NotImplementedError: Wrong number or type of arguments for overloaded function 'InstantCamera_RetrieveResult'.
  Possible C/C++ prototypes are:
    Pylon::CInstantCamera::RetrieveResult(unsigned int,Pylon::CGrabResultPtr &,Pylon::ETimeoutHandling)
    Pylon::CInstantCamera::RetrieveResult(unsigned int,Pylon::CGrabResultPtr &)

![imagen](https://user-images.githubusercontent.com/30239144/55321624-76f4aa80-547a-11e9-9109-e2a3741139ec.png)

Thank you in advance for any help you can provide

**Comment by thiesmoeller** [comment]
@LucasJulio and @Acam8 the documentation states "INFINITE" value. This is a windows specific define from winbase.h, which is not available on linux and didn't made it directly into the pypylon bindings.

#define INFINITE            0xFFFFFFFF  // Infinite timeout

If you would really put inf ( inf .. not INFINITY) even in C++ this would typecast from float to int to the value 0x80000000 which is not "forever" but just ~24days.

 
in pypylon you could either use the the value 0xFFFFFFFF  or use the following predefined constant:

```
>>> import pypylon.pylon as py
>>> py.waitForever
4294967295
>>> hex(py.waitForever)
'0xffffffff'
>>> 

```
