### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Eyshika** [basler/pypylon#102]
Am using it with pylon in the gui, where 1 click starts the camera video, and then process opencv fuctions on each frame, but it gives memory leak and crashed the system.
The way it is written is : 
`from pypylon import pylon 

def acquire_movie(self,numFrames,checkHsize,checkWsize):
        movie = []
      
        # for particular number of frames
        self.cap.StartGrabbing(numFrames)
        
        converter = pylon.ImageFormatConverter()

        #converting to opencv
        converter.OutputPixelFormat = pylon.PixelType_BGR8packed
        converter.OutputBitAlignment = pylon.OutputBitAlignment_MsbAligned

        while self.cap.IsGrabbing():
            self.grabResult = self.cap.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
            if self.grabResult.GrabSucceeded():
                
                image = converter.Convert(self.grabResult) #cv.cvtColor(self.grabResult.Array, cv.COLOR_BAYER_BG2RGB)
                self.rgb = image.GetArray()
                
              #  #some opencv process
                movie.append(self.rgb)
        return movie
```

class StartWindow(QtGui.QMainWindow):
#some opencv functions and button algorithm to start camera.
self.movie_thread = MovieThread(self.camera)
self.update_timer = QtCore.QTimer()
self.movie_thread.start()
self.update_timer.start(10)

class MovieThread(QtCore.QThread):
    #separate thread to keep imshow running properly
    def __init__(self,camera):
        super().__init__()
     
        self.camera = camera
    def run(self):
        
        self.camera.acquire_movie(3000,self.checkHsize,self.checkWsize)    
    
`

```
am doing multithreading to avoid memory issues, but it is still doing it. What is the reason ? something wrong in pypylon package ?

**Comment by thiesmoeller** [comment]
Hi @Eyshika ,

as a quick look at your code:

a)
why do you make grabResult an instance variable? 
`self.grabResult = ...`

when you use it only in this little scope this is not needed.

b)
you have to release the grabResult activly back to pylon grab engine. Otherwise you run out of buffers after some frames.

```
while self.cap.IsGrabbing():
        grabResult = self.cap.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
        if self.grabResult.GrabSucceeded():
            
            image = converter.Convert(self.grabResult) #cv.cvtColor(grabResult.Array, cv.COLOR_BAYER_BG2RGB)
            grabResult.Release()
            self.rgb = image.GetArray()
            
            #  #some opencv process
            movie.append(self.rgb)
```

we found no way to release the buffer automatically when you write the code like above. There is a pattern with the python contextmanager which works...

```
with cam.RetrieveResult(1000) as result:
        img = result.GetArray()
        ....

```

**Comment by Eyshika** [comment]
@thiesmoeller  Thank you for your suggestions. Can you please explain what does the value passed to cam.RetrieveResult means ? in the examples i saw its 5000, so I used 5000 but you are using 1000 here, can you please explain what does this value refer too, I know it's not number of frames, since number of frames are being passed to cap.StartGrabbing().

**Comment by thiesmoeller** [comment]
It's the time to wait for a result in ms.


Eyshika Agarwal <notifications@github.com> schrieb am Mo., 8. Apr. 2019,
19:34:
