### ISSUE TITLE
How to calibrate the distortion in Monochrome basler camera using pypylon

### ISSUE THREAD

**Issue by s7prselv** [basler/pypylon#104]
I need to calibrate the Basler monochrome camera, using the circular grid pattern in pypylon using opencv.

**Comment by thiesmoeller** [comment]
Hi @s7prselv ,

The native datatype of images in pypylon is compatible to opencv ( ndarray) so you can use any opencv sample for calibration.

Just replace the opencv `cam.read()` calls by corresponding `camera.RetrieveResult` and `res.GetArray()` calls in pypylon.
