### ISSUE TITLE
FileAccess() class issue in python 3

### ISSUE THREAD

**Issue by robbarnsley** [basler/pypylon#106]
Unsure if this is the correct place to post, but in **genicam.py**:

The functions **_read()** and **read()** (ln 3797 and 3811) need to declare variable **buf** as a bytes literal, i.e. 

buf = b''

otherwise it throws a TypeError trying to append (buf+=) on ln 3803 and 3814.

Additionally, Python 3 doesn't like the xrange function call on ln 3798.

**Comment by thiesmoeller** [comment]
Thanks for reporting. We already fixed this issue in our internal master ..

**Comment by thiesmoeller** [comment]
Is released already
