### ISSUE TITLE
ExposureTime adjustment

### ISSUE THREAD

**Issue by TobyUllrich** [basler/pypylon#11]
How do you adjust the exposure time of the camera with the pypylon api

**Comment by gachiemchiep** [comment]
There is sample at https://github.com/basler/pypylon/blob/db2565094d6f40bf6bfc5791c4baa6f42019542c/tests/pylon_tests/usb/grabtest.py

I took the snip here

```
  # Set exposure time
    camera.Open()
    camera.ExposureTime.SetValue(100000)  # 100000 microsecond
    camera.Close()
```

Hope that help
