### ISSUE TITLE
Is it possible to parameterize parameters, save them in a file and load them each time the camera is accessed?

### ISSUE THREAD

**Issue by zamarjavier** [basler/pypylon#117]
Hello,

I want to fix some values on my Basler Dart camera. The idea is to save those parameters in a file and each time the camera is initialized, load those parameters by defoult.

Thank you so much.

**Comment by thiesmoeller** [comment]
If you want to do this without any programming.
Just open your device with pylon viewer. Change values as required and follow the documentation on Usersets.
They are stored in camera flash memory,
[user sets](https://docs.baslerweb.com/#t=en%2Fuser_sets.htm)

**Comment by thiesmoeller** [comment]
Programmatic way ... See this example

[Load save test](https://github.com/basler/pypylon/blob/master/tests/pylon_tests/emulated/loadandsavetest.py)
