### ISSUE TITLE
Frames of GigE camera are inaccessible 

### ISSUE THREAD

**Issue by mlix11** [basler/pypylon#132]
**Setup:**
- Virtual machine (KVM) with ubuntu14.04, ubuntu16.04, ubuntu 18.04 and debian 9
- NIC is bridged, so every virtual machine has a own IP
- Only one virtual machine is running 
- Camera: GigE acA1920 - 25gc
- pylon 5.0.12 and 5.2

**Issue:**
I am able to connect and configure the camera on every linux OS, but my script only receives images on ubuntu 14.04.
Through wireshark I found out, that the camera is sending the images back to the system with the IP 0.0.0.0. Unfortunate it looks like, every OS above 14.04 is dropping the packages. My concern is, that newer kernel versions are dropping UDP packages, which don't have an IP. 

Is it possible to set the destination IP, so it is sending to a valid IP and not to 0.0.0.0? I tried it with the standard genicam parameter, but it didn't worked.

```
identifier = str(self.configuration["identifier"])
factory = pylon.TlFactory.GetInstance()

ptl = factory.CreateTl("BaslerGigE")
device_info = ptl.CreateDeviceInfo()
device_info.SetPropertyValue("IpAddress", camera_ip)
camera_device = factory.CreateFirstDevice(device_info)
camera = pylon.InstantCamera(camera_device)
camera.Open()
camera.GetNodeMap().GetNode("GevSCDA").SetValue(int(ipaddress.ip_address("host_ip")))
```
I always get a **pylon.TimeoutHandling_ThrowException**. Is there some "hack" to solve this? Because pylonviewer is working in the VMs. Be aware, that I will not able to connect via serial number. 

Thank you.

**Comment by thiesmoeller** [comment]
Pylon viewer works ? Including streaming video?
Is the camera discovered directly , or do you have 
to give the device IP by hand?
Is the value in feature GevSCDA in the working case the same as in your sample code?

You can write more compact code;

`camera.GevSCDA = <intvalue>`

**Comment by matt4lieb** [comment]
Pylonviever is working and the camera and host are internal ips. Discovery is not possible because of network restrictions, so serial number is not possible. 

The value which is given to the GevSCDA is the int based IP of the host. In the example I just replaced the IP with a placeholders.

**Comment by thiesmoeller** [comment]
in your virtual machine, you can do simple wireshark capture when you run the pylonviewer.

And apply the following display filter:
`gvcp.cmd.writereg.bootstrapregister == 0x00000d18`

This will show the command, that sets the destination IP into the camera.

This should be the same, as in your programmatic use-case

**Comment by thiesmoeller** [comment]
![grafik](https://user-images.githubusercontent.com/5516325/60462980-03b22e80-9c4b-11e9-8163-93cab2ecc43a.png)

**Comment by matt4lieb** [comment]
It probably does something to have with the StartGrabbing method. Because, when I am setting the destination ip it sends the request out to the GigE camera and when I call the StartGrabbing function it overwrites it. Do I have to do something different then `self.camera.StartGrabbing(pylon.GrabStrategy_LatestImageOnly)` ? 
After setting the destination IP with `self.camera.GetNodeMap().GetNode("GevSCDA").SetValue(int(ipaddress.ip_address("10.1.11.251"))`
![Screenshot of QEMU at 2019-07-02 09:16:05](https://user-images.githubusercontent.com/4290674/60494968-304c6180-9cb0-11e9-9183-cff05cc2d4c0.png)
After StartGrabbing
![Screenshot of QEMU at 2019-07-02 09:15:55](https://user-images.githubusercontent.com/4290674/60494970-304c6180-9cb0-11e9-8963-2b5ae768bdcf.png)

The both commands are in the same order in the script, no other code is executed between them.

**Comment by matt4lieb** [comment]
I also tried it with the pylon/Grab example and it is still the same issue with the Destination Address: 0.0.0.0
```
// Only look for GigE cameras.
CDeviceInfo info;
info.SetDeviceClass( BaslerGigEDeviceClass );
info.SetPropertyValue("IpAddress", "10.1.14.82");
// Create an instant camera object with the camera device found first.
CInstantCamera camera( CTlFactory::GetInstance().CreateFirstDevice(info));
        

// Print the model name of the camera.
cout << "Using device " << camera.GetDeviceInfo().GetModelName() << endl;
....

```

**Comment by thiesmoeller** [comment]
What is the Wireshark trace in the working pylon viewer case?

Regarding your code: pylon sets SCDA internally on startgrabbing.

**Comment by matt4lieb** [comment]
It looks good, with the correct IP. Is maybe the library doing something with sys-calls in the background, which can be blocked or in another format caused by the VM?

**Comment by matt4lieb** [comment]
Is there are python function to call this method, like in c++?

`bool ret = gigeTL->AnnounceRemoteDevice("x.x.x.x", &info);`

**Comment by kobotschick** [comment]
Do you found a solution to run pylon a VM?

**Comment by IvanVishev** [comment]
Hello all!
I have already mentioned this problem in another issue about the 0.0.0.0 problem. 
I have almost the same configuration as OP and have the same problems. Does anyone have a solution?

**Comment by IvanVishev** [comment]
I have investigated furhter on this problem. The same error with dest ip occurs also in pylon viewer. I am not sure,  but i think its a problem of ubuntu working on VM. Same camera works perfectly if accessed from Windows VM.

**Comment by mlix11** [comment]
If you are using a qemu VM + NAT, you have to set the correct SNAT (e.g. iptables). Otherwise, it will not be able to find the camera.
