### ISSUE TITLE
pylon IP Configurator doesn't work (No devices found!)

### ISSUE THREAD

**Issue by gustavoponce7** [basler/pypylon#133]
I want to set a static IP address in my camera (daa2500-14um) but the "pylon IP Configurator" doesn't find any device

The software displays en0, awdl0, utun0 and en5 but all of them display "**No devices found!**"

<img width="805" alt="ipConfigurator" src="https://user-images.githubusercontent.com/7660403/60523463-5ffb6980-9cb0-11e9-99f8-ea7f3bf44d77.png">

Do I have to install something else in order to see the camera?

BTW I have tried on Mac, Linux and Windows and I am getting the same behavior

Thanks

**Comment by thiesmoeller** [comment]
You have a USB camera in your hands (daa2500-14um).
USB has a host/device architecture and doesn't need a network layer to communicate.
The IP configurator is only for GigeVision (Ethernet + IP) devices.
