### ISSUE TITLE
how to set white balance auto 

### ISSUE THREAD

**Issue by Thyagutamizhan** [basler/pypylon#138]

**Comment by MattsProjects** [comment]
Have a look at issue #146. There is a good explanation of using the user documentation to find information on the feature, and then going from the C++ code snippet to pypylon (the api's are identical save for the language).

**Comment by wweertman** [comment]
I also am having this issue. I was unable to follow this issue and find a solution. The C++ code for auto white balance in the GUI does not seem to translate directly to python. So I imagine it is just a syntax issue..

**Comment by sjiang95** [comment]
There are sample codes for C/C++, etc. [Balance White Auto | Basler](https://docs.baslerweb.com/balance-white-auto#__tabbed_2_1). But don't know the corresponding interface in python.

**Comment by thiesmoeller** [comment]
The mapping from c++ to python for *feature* access is really search and replace by this rule https://github.com/basler/pypylon/issues/505#issuecomment-1150780559
