### ISSUE TITLE
module 'pypylon.pylon' has no attribute 'PylonImageWindow'

### ISSUE THREAD

**Issue by brtasavpatel** [basler/pypylon#14]
I was trying to run this sample code:

https://github.com/basler/pypylon/blob/master/samples/guiimagewindow.py#L6

but pylon module doesn't have an attribute called PylonImageWindow.

**Comment by thiesmoeller** [comment]
Assuming you run pypylon on Linux?
In the current setup. PylonImageWindow is only available/compiled in on windows. 

see [setup.py](https://github.com/basler/pypylon/blob/master/setup.py#L342)

I would recommend to use an opencv or PyQt GUI
