### ISSUE TITLE
Get max image width, height

### ISSUE THREAD

**Issue by keven425** [basler/pypylon#141]
I'm trying to get the max image width/height of a camera, i.e. the default number of pixels for a given sensor. `camera.Width.Max` does not seem to return the maximum width. Instead, it returns the previously set `camera.OffsetX + camera.Width`.

Any idea on this?

**Comment by thiesmoeller** [comment]
Pylon won't let you set invalid values. This is why e.g. width max is clipped by offset.
To get the sensor max:
You could just set Offset to '0' and query afterwards or just 
ask the camera manual : 
https://docs.baslerweb.com/#t=en%2Fdevice_information_parameters.htm&rhsearch=Sensorwidth&rhhlterm=Sensorwidth
