### ISSUE TITLE
Pypylon and pylon mono8 image format

### ISSUE THREAD

**Issue by PolymaTh-EE98** [basler/pypylon#142]
Is the mono8 image format 3 channels? I’m using a line scan camera (runner I believe) and the image comes back 3 channels. Is that how the genicam standard also handles mono? It is quite vague... if it supposed to be single channel can assist me in finding the correct settings?

**Comment by thiesmoeller** [comment]
A brief look into your camera manual is the first step :-) 

Mono is normally single channel data.

**Comment by PolymaTh-EE98** [comment]
Then I have a software or a user error. Even in the pylon viewer when I hover over a mono8 image I get RGB values in the lower right. I asked another long time user and he also said it is 3 channel for him. What setting do I change to have mono8 behave as expected?

**Comment by thiesmoeller** [comment]
What is the Pixelformat that you configure?

**Comment by thiesmoeller** [comment]
no feedback since 2019
