### ISSUE TITLE
Grabbing video from multiple camera setup using HW Master-Slave array

### ISSUE THREAD

**Issue by elhananby** [basler/pypylon#143]
Hi everyone, I tried to search a bit about my issue, however I could not find something directly related (i think).
My current setup has three USB cameras, wired in a master-slave setup - when manually triggering the master camera in pylon, the other two start triggering along with it.
However, I am not sure in pypylon how can I actually get the image data - using the multigrab example, the cameras are still all SW triggered. How can I retrieve the grab data from all three cameras concurrently, rather than one-by-one?
I guess the main bottleneck in this setup would be the fact that the PC still has to send a trigger to the master camera, but since I don't need a very high FPS I assume that won't be an issue?

Thanks

**Comment by Curmen** [comment]
> Hi everyone, I tried to search a bit about my issue, however I could not find something directly related (i think).
> My current setup has three USB cameras, wired in a master-slave setup - when manually triggering the master camera in pylon, the other two start triggering along with it.
> However, I am not sure in pypylon how can I actually get the image data - using the multigrab example, the cameras are still all SW triggered. How can I retrieve the grab data from all three cameras concurrently, rather than one-by-one?
> I guess the main bottleneck in this setup would be the fact that the PC still has to send a trigger to the master camera, but since I don't need a very high FPS I assume that won't be an issue?
> 
> Thanks

Hello elhananby,
 I also faced same problem. Could you please explain how to solved this problem. 

 Best regards.
