### ISSUE TITLE
A code to get B, G, R and depth matrix?

### ISSUE THREAD

**Issue by sedhha** [basler/pypylon#147]
Hi I used to run your openCv code in python and it worked well. But it's throwing the gray scale image. I just wanted to know if there's any way I can obtain depth matrix? That would be really helpful. 

Thanks in advance.

**Comment by thiesmoeller** [comment]
As the functionality of pypylon depends on the model you use. Always report the model you use.

**Comment by thiesmoeller** [comment]
No further action on this issue
