### ISSUE TITLE
Support for getting coreboard temperature

### ISSUE THREAD

**Issue by thedim-witted** [basler/pypylon#154]
I couldn't find a python api for reading the coreboard temperature and was wondering if there is a way to do it.

**Comment by thiesmoeller** [comment]
It's a feature of your camera, that will just be made available by pypylon.
So check on docs.baslerweb.com the name of the feature for your model ...

**Comment by thedim-witted** [comment]
Yes, there is a feature but I need a python API to use it in my script. All I could find is C and C++ commands.

**Comment by thiesmoeller** [comment]
As you don't mention your camera model, I can't give you the exact answer.....

But if the documentation states:
```
// Get the current device temperature
double d = camera.DeviceTemperature.GetValue();
```

in python it is just
```
# Get the current device temperature
d = camera.DeviceTemperature.GetValue()
```

All camera functions are always exactly as their C++ counterpart. because the API is coming from your camera itself.

**Comment by thedim-witted** [comment]
I did the same by using the commands mentioned in the documentation. But it throws an error when I tried to initialize the temperature sensor. However, I guess I don't have to do that step in python and directly read the value.

**Comment by thiesmoeller** [comment]
Please mention the camera model in issue tickets, so an exact answer is possible.

**Comment by rohitrkr** [comment]
@thedim-witted did you find any solution for the same..??
not able to get device temperature by this line of code in python camera.DeviceTemperature.GetValue()
my devce model number is acA1920-40gc.
@thiesmoeller

**Comment by ckldas** [comment]
@thedim-witted @thiesmoeller Pls help......

**Comment by ckldas** [comment]
Not able to Read Basler Camera Core Board Temperature Via pypylon

**Comment by ckldas** [comment]
yes

**Comment by ckldas** [comment]
@thedim-witted u closed this issue. Pls let me know if u got the exact solution.

**Comment by thiesmoeller** [comment]
@ckldas 
As you can read in pylon viewer, you can also read in pypylon

In the pylon viewer documentation panel there is always a C++ snippet, that you can copy nearly 1:1

As you never copied your error message it is hard to support

**Comment by ckldas** [comment]
d = camera.DeviceTemperature.GetValue()

Error is "camera dont have attribute DeviceTemperature".

**Comment by thiesmoeller** [comment]
as this is not an error message, that pypylon would throw ....

here is a short demo code to show the temperature sensors of a camera:
```python
import pypylon.pylon as py

tlf = py.TlFactory.GetInstance()
cam = py.InstantCamera(tlf.CreateFirstDevice())

cam.Open()
print(cam.DeviceModelName.Value)

temp_sens = cam.DeviceTemperatureSelector.Symbolics

for sens in temp_sens:
    cam.DeviceTemperatureSelector = sens
    temp = cam.DeviceTemperature.Value 
    print(f"{sens} temp is {temp}°C")

```

**Comment by rohitrkr** [comment]
@thiesmoeller thnx buddy for your responses....
Partially Its working

**Comment by thiesmoeller** [comment]
What part of "getting core board temp" is not working?

rohitrkr ***@***.***> schrieb am Di., 24. Mai 2022, 16:32:

**Comment by jvermaEt** [comment]
my system have multiple camera connected how should i get all camera temperature acA402024  usb

**Comment by SMA2016a** [comment]
why do not open a new thread for new case?

Please refer document page 👍 
https://docs.baslerweb.com/device-temperature#python_2

if this code line fails to read the value, check with pylonviewer if your camera has got this feature
