### ISSUE TITLE
Grab multiple images via hardware trigger,  grabResult.Release() does not work properly

### ISSUE THREAD

**Issue by lmkrieg** [basler/pypylon#155]
try:

camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
    camera.RegisterConfiguration(pylon.ConfigurationEventHandler(), pylon.RegistrationMode_ReplaceAll, pylon.Cleanup_Delete) 
    camera.Open()
    camera.AcquisitionMode.SetValue('SingleFrame')
    camera.TriggerMode.SetValue('On')
    print("Using device ", camera.GetDeviceInfo().GetModelName())
    camera.MaxNumBuffer = 10
    camera.StartGrabbingMax(countOfImagesToGrab, pylon.GrabStrategy_OneByOne)

    while camera.IsGrabbing():
        grabResult = camera.RetrieveResult(time_in_milli, pylon.TimeoutHandling_ThrowException)
        if grabResult.GrabSucceeded():          
           Image.fromarray(grabResult.Array).save(r"C:\HIL\Universal\Tools\LightEvaluation\GlareFreeHighBeam\Initialization_Images\Image_%d.png" %image_counter)
            image_counter=image_counter+1
            print image_counter
        else:
            print("Error: ", grabResult.ErrorCode, grabResult.ErrorDescription)
        print ('Saved')
        grabResult.Release()
        print('Released')

Hello,

I have the following problem: I want to take several shots in a row and save them in a folder. The first picture is saved as expected. Then python stops at the grabResult.Release() code line and waits until the GrabTime has expired. As soon as the time has expired, 'Released' will be printed. Does anyone have any idea how to fix this issue.

**Comment by thiesmoeller** [comment]
You have to use continuous not singleframe mode

**Comment by lmkrieg** [comment]
Thank you.
