### ISSUE TITLE
Using pypylon on raspberry pi 4 or other arm64?

### ISSUE THREAD

**Issue by Dev-Solitech** [basler/pypylon#164]

**Comment by thiesmoeller** [comment]
pypylon works perfectly on raspberry pi 4 and other arm64 platforms

For wheels check in https://github.com/basler/pypylon/releases
e.g.
https://github.com/basler/pypylon/releases/download/1.5.1/pypylon-1.5.1-cp37-cp37m-linux_aarch64.whl

**Comment by VervenneThomas** [comment]
@thiesmoeller Hi, I tried using the wheel you suggested on a raspberry pi4. Unfortunately the wheel is not supported.

**Comment by thiesmoeller** [comment]
It was a 'e.g.' wheel.
Check the python version on your rpi4.
The wheel is named accordingly. E.g. 
cp37 stands for python 3.7

**Comment by james0807** [comment]
@thiesmoeller Hi, I'm having the same issue, my python version is 3.7 on the Pi 4, but I'm getting the "not supported on this platform error". I think the Pi is a 32 bit system, could that be the problem?

**Comment by james0807** [comment]
@VervenneThomas Hi, did you get anywhere with this? Did you get any of the wheels to install properly on the Pi 4?

**Comment by thiesmoeller** [comment]
As we only build for arm64 ... Just compile the module

**Comment by james0807** [comment]
Okay so there are no pre-built wheels for Raspberry Pi 4? Doesn't bother me just making sure I've understood and that this is clear in case anyone comes looking for something similar.

Thanks :)

**Comment by thiesmoeller** [comment]
No. You asked for arm32 binaries...
Pi4 with arm64 is available ....

**Comment by james0807** [comment]
Not officially though? Raspbian is 32 bit unless i'm completely lost!

**Comment by Dev-Solitech** [comment]
[image: image.png]
Raspberry pi 4 using this wheels.
cp3.... is your python version.
Hope this helps.

ในวันที่ พฤ. 5 มี.ค. 2020 เวลา 16:52 james0807 <notifications@github.com>
เขียนว่า:

**Comment by thiesmoeller** [comment]
As I use all boards on aarch64 ... Slighty misinformed. Check the armv7 builds. These are your arm32 bit builds

**Comment by james0807** [comment]
Excellent thank you. How are you running on 64 bit?

**Comment by thiesmoeller** [comment]
There are multiple distributions that provide 64 bit. Raspian main is still
on 32bit for compatibility reasons.

james0807 <notifications@github.com> schrieb am Do., 5. März 2020, 14:23:
