### ISSUE TITLE
How to make the program like ParameterizeCameraSample

### ISSUE THREAD

**Issue by HajimeMiyata** [basler/pypylon#172]
I want to make py sample that can access camera's all parameters like cpp sample program ParametrizeCamera_GenericParameterAccess.cpp.

We want to change the setting of ExposureAuto and WhiteBalanceAuto via python.

[ParametrizeCamera_GenericParameterAccess.txt](https://github.com/basler/pypylon/files/3840682/ParametrizeCamera_GenericParameterAccess.txt)

**Comment by thiesmoeller** [comment]
Please take a look into the samples or the readme.

You can access all parameters directly by its name.
e.g.
`camera.ExposureAuto = "Off"`
or
`camera.Width = 1920`

The names are completely identical to C++

**Comment by HajimeMiyata** [comment]
[grab_ExposureAuto_WhiteBalanceAuto.txt](https://github.com/basler/pypylon/files/3844686/grab_ExposureAuto_WhiteBalanceAuto.txt)

Thank you for your answer!.
Now, I can make python program to set ExposureAuto and WhiteBalanceAuto at Once.
