### ISSUE TITLE
Module not found: No module named 'pypylon

### ISSUE THREAD

**Issue by ljc1313** [basler/pypylon#174]
I am using win 64, and Python 3.6.8- I am new to python and modules and getting error;
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from pypylon import pylon
ModuleNotFoundError: No module named 'pypylon'

I saw  there were other similar issues raised but it appears they all referred to Linux OS not windows

I am trying to run grab.py btw.

**Comment by thiesmoeller** [comment]
What is your IDE ?
How did you install pypylon ?

**Comment by ljc1313** [comment]
I am using IDLE (Python Shell 3.8)

**Comment by thiesmoeller** [comment]
How did you install pypylon ?

**Comment by thiesmoeller** [comment]
> I am using win 64, and Python 3.6.8

.... pypylon-1.5.1-cp33pcp33m-win32.whl
is pypylon for 
cp33 [ cpython version 3.3 ]

and the win32 .... says its for win 32

The installation is described in the readme on : https://github.com/basler/pypylon

BUT:
at the moment we have no binary built for python 3.8
So you have two options:

a) compile yourself from source ....
b) uninstall the python3.8 install and install a python 3.7 
   this is still fully maintained ...
 https://www.python.org/downloads/release/python-375/)
 and then you can use this wheel 
https://github.com/basler/pypylon/releases/download/1.5.1/pypylon-1.5.1-cp37-cp37m-win_amd64.whl

**Comment by ljc1313** [comment]
Ok 

I will install win 64 version, pypylon-1.5.1-cp36-cp36m-win_amd64.whl

I will uninstall python 3.8 and go to 3.7

**Comment by thiesmoeller** [comment]
no ;-)

pypylon-1.5.1-cp36-cp36m-win_amd64.whl
This is for python 3.6
you need 
pypylon-1.5.1-cp37-cp37m-win_amd64.whl

**Comment by ljc1313** [comment]
Ahh, I see

ran pip3 install pypylon-1.5.1-cp37-cp37m-win_amd64.whl

and pypylon installed successfully

thanks thiesmoller,
 
I will see if grab.py will run now

**Comment by ljc1313** [comment]
I had to make a couple additional installs to get grab.py to run normally
1) had to run (in cmd)
python.exe -m pip install numpy 
and
2)had to run (in cmd)
python -m pip install --upgrade pip 
as I had an older version of pip causing issues as well

Thanks thiesmoller
