### ISSUE TITLE
issue in installing  pypylon on ubuntu 18.04 

### ISSUE THREAD

**Issue by Harshal0907** [basler/pypylon#176]
pip3 install pypylon
Collecting pypylon
  Could not find a version that satisfies the requirement pypylon (from versions: )
No matching distribution found for pypylon

i tried to install the pypylon package on the ubuntu 18.04 it is giving me above error 
what will be the solution for it
thanks in advance

**Comment by Zhefei777** [comment]
Hi, I don't know if you have fixed that. 
But you can't just install pypylon with pip3 install pypylon
and you have to install swig first.
