### ISSUE TITLE
How can i set exposure Time via python

### ISSUE THREAD

**Issue by Curmen** [basler/pypylon#181]
Hello,
 I try to understand basler raL2048-48gm these couple of days. So every i plug off and on the power in camera. Exposure time set 14 ms. But i want to configure just once and the exposure time should be same when i power off and on the camera.  
 So in my .py application i already try but it didn't help. 

```
camera.AutoExposureTimeAbsLowerLimit.SetValue(1000)
camera.AutoExposureTimeAbsUpperLimit.SetValue(5000)
camera.AutoTargetValue.SetValue(128);
camera.ExposureAuto.SetValue(ExposureAuto_Continuous)

```

**Comment by thiesmoeller** [comment]
Read the section about UserSets/Configuration Sets in the camera manual.
You can change settings. Store them in one of three flash locations in the camera and configure your camera to boot the next time with these settings.

**Comment by thiesmoeller** [comment]
If you want to let the camera start with a given set of configuration:
e.g. always start with 20ms exposuretime for the next boot

```
camera.ExposureTimeAbs = 20000

camera.UserSetSelector = "UserSet1"
camera.UserSetSave.Execute()
camera.UserSetDefaultSelector = "UserSet1"
```

**Comment by Curmen** [comment]
Thank you so much moeller. Both commands help me
