### ISSUE TITLE
problem in installing pypylon in python 3.8 

### ISSUE THREAD

**Issue by ali-atghaei** [basler/pypylon#187]
hi. I cant install pypylon neither with pip nor with its binary release in Windows(32 bit). 
in its binary release when i run ( python setup.py install ) it returns error and with (pip install . ) it says "ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output." 
what should I do for installing pypylon in python 3.8 ? I have force to use python 3.8.
I try each wheel version in pypi.
i have installed visual studio and swig and have added their path in my system. 
thanks for helps.

**Comment by nmarc** [comment]
On Linux or Windows?

Ali Atghaei <notifications@github.com> schrieb am So., 15. Dez. 2019, 14:16:

**Comment by ali-atghaei** [comment]
on Windows

**Comment by nmarc** [comment]
Can you pleased try winpython
Version "WinPython64-*3.8*.0.0cod"

And Install via pip
( Set Proxy If needed)
C:\python -m pip install pypylon


Ali Atghaei <notifications@github.com> schrieb am So., 15. Dez. 2019, 14:30:

**Comment by ali-atghaei** [comment]
I tried it. says : 
ERROR: Could not find a version that satisfies the requirement pypylon (from ver
sions: none)
ERROR: No matching distribution found for pypylon

**Comment by nmarc** [comment]
Which Pylon Version is installed ?

Ali Atghaei <notifications@github.com> schrieb am So., 15. Dez. 2019, 14:39:

**Comment by ali-atghaei** [comment]
pylon V5

**Comment by amalsafa** [comment]
@ali-atghaei  I tried to install pypylon on Raspberry but i faced the same issue as you, please did you find a solution for that?

**Comment by thiesmoeller** [comment]
Beginning with release 1.7.1 we have binary releases on all platforms, that you can install via pip.

update your pip version before by calling `python -m pip install --upgrade pip`
