### ISSUE TITLE
when pypylon whl file release for python 3.8

### ISSUE THREAD

**Issue by ali-atghaei** [basler/pypylon#188]
I cant install pypylon in python 3.8 . when will it release?

**Comment by lrwilt** [comment]
I'm also interested if the whl file for Python 3.8 will be available soon. I'm running 3.8.1 with Pylon6 on a Windows 10 machine.

**Comment by saikatpph** [comment]
I have managed to compile pypylon from the source code and using with python 3.8.1 (windows 64 bit). Please check my repository, and let me know if those files could solve your issue. Thanks.

**Comment by thiesmoeller** [comment]
is released
