### ISSUE TITLE
how to connect remote device which not in the subnet

### ISSUE THREAD

**Issue by pythonfucku** [basler/pypylon#19]
hello：
    I need to connect remote device, I have the camera's IP, but the device not in the subnet, and I did not found "CBaslerGigEDeviceInfo" , "IGigETransportLayer"  or other interface about GigE in pypylon.

    So, how to connect?

**Comment by GuzziButz** [comment]
Hi pythonfucku, AFAIK there's actually no way to connect to a GigE Vision camera which is _not_ in the same subnet. You need to configure your camera  to be in the same subnet (e.g. with the pylon IP Configurator) as your host device,

**Comment by thiesmoeller** [comment]
Solution that @netanelf provides solves the issue
