### ISSUE TITLE
Can't add property to child class when inheriting pylon.InstantCamera

### ISSUE THREAD

**Issue by hank-der-hafenarbeiter** [basler/pypylon#196]
Hey everyone,

I'm running into issues when trying to inherit `pylon.InstantCamera`. Adding methods in the child class works fine, but I need to add a `threading.Lock` as well. 

    import threading
    import pylon
    
    class MyCamera(pylon.InstantCamera):
    
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kargs)
            self.lock = threading.Lock()

Now when I call `MyCamera()` the program crashes on `self.lock = threading.Lock()` with `LogicalErrorException: Node not existing [...]`. Even if I move the lock definition up to the top of `__init__()` I get `TypeError: in method 'InstantCamera_GetNodeMap', argument 1 of Type 'Pylon::CInstanCamera *'`.

I found a workaround by adding the variable to the objects `__dict__` directly:

    import threading
    import pylon
    
    class MyCamera(pylon.InstantCamera):
    
        def __init__(self, *args, **kwargs):
            self.__dict__['lock'] = threading.Lock()
            super().__init__(*args, **kargs)

But I don't know if this will have any weird side effects.

Is there a better way to do this? Is this way safe to use?

**Comment by thiesmoeller** [comment]
Subclassing of Instant camera is not supported.

Please use the InstantCamera as Member in your MyClass 

Reason for the issues you saw is the dynamic feature lookup to realize the

`cam.Gain = 42
`
functionality
