### ISSUE TITLE
Saving images grabbed from camera

### ISSUE THREAD

**Issue by glin123** [basler/pypylon#20]
Hello;

I'm trying to take image from my new basler camera and save them to a certain folder. I can capture them but I'm not quite sure on how to save them. If anyone has anyone info on this topic please let me know. Thank you.

**Comment by matt-phair** [comment]
Here's how I do it:

```python
from PIL import Image
from pypylon import pylon

camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
camera.Open()
camera.PixelFormat = "Mono12"
camera.StartGrabbingMax(1)
try:
  while camera.IsGrabbing():
    result = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
    if result.GrabSucceeded():
      try:
        Image.fromarray(result.Array).save("/path/to/file.extension")
      finally:
        result.Release()
finally:
  camera.StopGrabbing()
  camera.close()
```

**Comment by cache91** [comment]
the above code doesnt seem to work

**Comment by matt-phair** [comment]
>the above code doesnt seem to work

I didn't test it as the main important part I was trying to convey was the `Image.fromarray()` call. What problem are you running into with it?

**Comment by cache91** [comment]
looks like the tiff format only works. Other formats fail

**Comment by matt-phair** [comment]
Typo...should be `camera.Close()`
