### ISSUE TITLE
Getting an error while trying compiling from the source code

### ISSUE THREAD

**Issue by saikatpph** [basler/pypylon#203]
**I am using Python 3.8, and would like to install the pypylon. Since there is no binding available for the Python 3.8 version, I was trying to compile it from the source code, following the instruction:
     " git clone https://github.com/basler/pypylon.git
       cd pypylon
       pip install . "
However, I am encountering the following issue
Any suggestion to fix this issue?
Thanks**

  ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikat\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-req-build-hr_b3q_w\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-req-build-hr_b3q_w\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pip-egg-info'
         cwd: C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\
    Complete output (45 lines):
    fatal: not a git repository (or any of the parent directories): .git
    WARNING:root:git not found or invalid tag found.
    WARNING:root:-> Building version from date!
    NodeCallback.i(166) : Warning 401: Nothing known about base class 'CNodeCallback'. Ignored.
    IPort.i(23) : Warning 403: Class 'GENAPI_NAMESPACE::IPort' might be abstract, no constructors generated,
    C:\Program Files\Basler\pylon 6\Development\include\GenApi\IBase.h(57) : Warning 403: Method GENAPI_NAMESPACE::IBase::GetAccessMode() const might not be implemented.
    PortImpl.i(52) : Warning 403: Class 'GENAPI_NAMESPACE::CPortImpl' might be abstract, no constructors generated,
    C:\Program Files\Basler\pylon 6\Development\include\GenApi\IBase.h(57) : Warning 403: Method GENAPI_NAMESPACE::IBase::GetAccessMode() const might not be implemented.
    C:\Program Files\Basler\pylon 6\Development\include\pylon\gige\ActionTriggerConfiguration.h(71) : Warning 325: Nested struct not currently supported (ActionParameter ignored)
    ..\genicam\NodeCallback.i(166) : Warning 401: Nothing known about base class 'CNodeCallback'. Ignored.
    ..\genicam\IPort.i(23) : Warning 403: Class 'GENAPI_NAMESPACE::IPort' might be abstract, no constructors generated,
    C:\Program Files\Basler\pylon 6\Development\include\GenApi\IBase.h(57) : Warning 403: Method GENAPI_NAMESPACE::IBase::GetAccessMode() const might not be implemented.
    ..\genicam\PortImpl.i(52) : Warning 403: Class 'GENAPI_NAMESPACE::CPortImpl' might be abstract, no constructors generated,
    C:\Program Files\Basler\pylon 6\Development\include\GenApi\IBase.h(57) : Warning 403: Method GENAPI_NAMESPACE::IBase::GetAccessMode() const might not be implemented.
    C:\Program Files\Basler\pylon 6\Development\include\pylon\PylonImageBase.h(38) : Warning 403: Class 'Pylon::CPylonImageBase' might be abstract, no constructors generated,
    C:\Program Files\Basler\pylon 6\Development\include\pylon\ReusableImage.h(50) : Warning 403: Method Pylon::IReusableImage::IsSupportedPixelType(Pylon::EPixelType) const might not be implemented.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\setup.py", line 900, in <module>
        bs.copy_runtime()
      File "C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\setup.py", line 481, in copy_runtime
        super(BuildSupportWindows, self).copy_runtime()
      File "C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\setup.py", line 211, in copy_runtime
        shutil.copytree(src, dst)
      File "c:\users\saikat\appdata\local\programs\python\python38\lib\shutil.py", line 546, in copytree
        with os.scandir(src) as itr:
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Basler\\pylon 6\\Development\\..\\runtime\\x64\\pylonCXP'
    Building version: 2020.2.12.dev41131
    Remove: .\generated
    Remove: .\pypylon
    call C:\Users\Saikat\Downloads\swigwin-4.0.1\swigwin-4.0.1\swig.exe -python -outdir C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon -o C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\generated\genicam_wrap.cpp -c++ -Wextra -Wall -threads -py3 -DHAVE_PYLON_GUI -D_WIN32 -D_WIN64 -IC:\Program Files\Basler\pylon 6\Development\include genicam.i

    call C:\Users\Saikat\Downloads\swigwin-4.0.1\swigwin-4.0.1\swig.exe -python -outdir C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon -o C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\generated\pylon_wrap.cpp -c++ -Wextra -Wall -threads -py3 -DHAVE_PYLON_GUI -D_WIN32 -D_WIN64 -IC:\Program Files\Basler\pylon 6\Development\include -IC:\Program Files\Basler\pylon 6\Development\include pylon.i

    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\PylonBase_v6_0.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\GCBase_MD_VC141_v3_1_Basler_pylon.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\GenApi_MD_VC141_v3_1_Basler_pylon.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\log4cpp_MD_VC141_v3_1_Basler_pylon.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\Log_MD_VC141_v3_1_Basler_pylon.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\NodeMapData_MD_VC141_v3_1_Basler_pylon.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\XmlParser_MD_VC141_v3_1_Basler_pylon.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\MathParser_MD_VC141_v3_1_Basler_pylon.dll => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\
    Copy tree C:\Program Files\Basler\pylon 6\Development\..\runtime\x64\pylonCXP => C:\Users\Saikat\AppData\Local\Temp\pip-req-build-hr_b3q_w\pypylon\pylonCXP
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by thiesmoeller** [comment]
Reinstall Pylon 6 and Install all transportlayers including cxp.

**Comment by saikatpph** [comment]
> Reinstall Pylon 6 and Install all transportlayers including cxp.

Thanks a lot !!! it Worked. :)
