### ISSUE TITLE
unable to install/import/use pypylon

### ISSUE THREAD

**Issue by thomaswenkin** [basler/pypylon#209]
Hi every one
I am trying to develop an application on Python with pypylon and a Gige Camera from Basler but I am unable to install pypylon using pip even though every requirement is met.

When I try to use pip to install it, I get this error message :
![image](https://user-images.githubusercontent.com/35154455/76205660-f77b6980-61fa-11ea-9dd7-48ea481a62b7.png)

Then if I try to directly unzip the wheel inside my site-packages folder, pip registers it and all like so :
![image](https://user-images.githubusercontent.com/35154455/76206078-addf4e80-61fb-11ea-902e-dfb88180b940.png)

And after that, trying to import the package fails even though the package is seen as available :
![image](https://user-images.githubusercontent.com/35154455/76206285-0282c980-61fc-11ea-9928-c1fff70880c0.png)
It seems that the _pylon directory is missing, as well as a dll file (which I assume is available inside my Pylon Viewer Installation directory)

I already installed Pylon Viewer twice, each time making sure that the SDK installing box was checked to be sure to meet the requirements.

Does anyone have a hint or something else to help me troubleshoot this?

Thanks in Advance

**Comment by thiesmoeller** [comment]
From the error message you try to load a module from a wrong CPU architecture or os.
..."is not a valid Win32 app...."

What is your os/system?
What whl file you tried to install?

**Comment by thomaswenkin** [comment]
I am feeling kinda dumb, my Python install was using Python 3.8 while Pypylon hasn't been ported to 3.8 yet...
I installed Python 3.7 and everything's fine now
