### ISSUE TITLE
Raspberry Pi use pypylon

### ISSUE THREAD

**Issue by txxxcds** [basler/pypylon#221]
I want use Raspberry Pi get image from basler cameras,but this issues show when I run sameples:
$:python3 grab.py
An exception occurred.
Traceback (most recent call last):
  File "grab.py", line 27, in <module>
    camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
  File "/usr/local/lib/python3.7/dist-packages/pypylon/pylon.py", line 1614, in CreateFirstDevice
    return _pylon.TlFactory_CreateFirstDevice(self, *args)
_genicam.RuntimeException: Failed to download the XML configuration file from device 'Basler acA1600-20gc#00305321D9DE#192.168.10.11:3956': Timeout, no message received. (0xE101800B) role=0
 : RuntimeException thrown (file 'BaslerGigETl.cpp', line 316)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "grab.py", line 68, in <module>
    print(e.GetDescription())
AttributeError: 'RuntimeException' object has no attribute 'GetDescription'

I use pypylon-1.5.1-cp37-cp37m-linux_armv7l.whl.Thanks

**Comment by stefanklug** [comment]
This doesn't look like a pypylon issue. 
I close this as it is too old. @txxxcds please reopen, if this is still an issue for you.
