### ISSUE TITLE
pylon.__version__ returns installation date instead of 1.5.4

### ISSUE THREAD

**Issue by yves-surrel** [basler/pypylon#224]
On MacOS X, pypylon 1.5.4
```
pylon.__version__
Out[2]: '2020.4.25.dev32572'
```
Is this the intended behavior?

**Comment by stefanklug** [comment]
This happens if you build from a tarball intead of a git checkout. During build pypylon looks for git tags to get the pypylon version.
So for the time beeing it is expected behaviour (although not ideal).
