### ISSUE TITLE
How to get frame exposure time?

### ISSUE THREAD

**Issue by asavpatel92** [basler/pypylon#23]
How can I get exposure time for a particular frame after grab is finished? I can get exposure time from the camera object but if camera exposure is changed by the time grab is finished. it would be a wrong exposure time for the frame.

**Comment by GuzziButz** [comment]
You can use the [data chunk ](url)Feature.

**Comment by GuzziButz** [comment]
here's the correct [link ](https://github.com/basler/pypylon/issues/23)to the feature documentation.
With grabchunkimage.py you'll find a related sample in the pypylon samples collection.

**Comment by asavpatel92** [comment]
@GuzziButz the link points to this same issue here. can you please point me to the documentation?

**Comment by asavpatel92** [comment]
nvm. I found the documentation in the SDK.
for anyone else looking for the answer.

this is how you can access the exposure time of the frame : 
`grabResult.GetChunkNode("ChunkExposureTime").Value`
