### ISSUE TITLE
pylon wheel 1.5.4 aarch64 contains 32bit library

### ISSUE THREAD

**Issue by scipioni** [basler/pypylon#242]
install pypylon wheel 1.5.4 on arm64
`
pip install --force https://github.com/basler/pypylon/releases/download/1.5.4/pypylon-1.5.4-cp38-cp38-linux_aarch64.whl
`

check shared library installed that is 32bit
`
file ~/venv/lib/python3.8/site-packages/pypylon/_pylon.cpython-38-arm-linux-gnueabihf.so
_pylon.cpython-38-arm-linux-gnueabihf.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1
`

**Comment by stefanklug** [comment]
Hi @scipioni,

thanks for the finding. It took a while but it is now resolved in the 1.6 release.
Cheers Stefan
