### ISSUE TITLE
disable white balancing and all other auto adjustments for daA4200-30mci

### ISSUE THREAD

**Issue by L-o-r-e-n-z** [basler/pypylon#245]
Hello all,

in February you updated the driver packages for the daA4200-30mci camera type. There you implemented the exposure and gain adjustment possibility and to also disable the auto adjustment. Is it possible that you also implement other auto adjustments or especially the disabling of this? How is the chance to implement those features soon?

Thank you for your support

**Comment by FrankKarstens** [comment]
Hi L-o-r-e-n-z,
we regularly implement new features on customer requests but prioritized by the feature's usefulness for the majority of our customers. Maybe we can discuss your needs offline: mailto:frank.karstens@baslerweb.com

**Comment by stefanklug** [comment]
Discussion moved to other channel. 
@L-o-r-e-n-z  we added manual white balance in the current software (CEP 1.4)

**Comment by HosseinSD** [comment]
I also need to disable auto white balance, is this feature added yet?
