### ISSUE TITLE
run error after pyinstaller  XXX.py

### ISSUE THREAD

**Issue by Michelangelo-Y** [basler/pypylon#252]
The demo.py run in pycharm is OK,but after turn to demo.exe use pyinstaller,demo.exe can't find device(i have all .dll need) here is the error tips:
No device is available or no device contains the provided device info properties. : RuntimeException thrown

**Comment by Michelangelo-Y** [comment]
solved by https://github.com/basler/pypylon/issues/36#issuecomment-491837230

**Comment by stefanklug** [comment]
Great that it got solved...
