### ISSUE TITLE
Get current camera timestamp

### ISSUE THREAD

**Issue by mmvve** [basler/pypylon#272]
Hello,
how do you access the current ticks count of the camera?
Unfortunately I don't have the camera (basler ace, usb) to test it and I have to deploy remotely.
I'm looking for the equivalent of this but within pypylon:
```
// Take a "snapshot" of the camera's current timestamp value
camera.TimestampLatch.Execute();
// Get the timestamp value
int64_t i = camera.TimestampLatchValue.GetValue();
```
(from https://docs.baslerweb.com/timestamp)
Is there such thing?
Thank you

**Comment by thiesmoeller** [comment]
replace '//' -> '#'
replace ';' -> ''
Variables are dynamically typed
;-)


```
# Take a "snapshot" of the camera's current timestamp value
camera.TimestampLatch.Execute()
# Get the timestamp value
i = camera.TimestampLatchValue.GetValue()
```
