### ISSUE TITLE
clicked image has line patches. This happens in ~~ 5 / 50 images. 

### ISSUE THREAD

**Issue by deepampatel** [basler/pypylon#276]
![2020-09-14 19:31:37 804930](https://user-images.githubusercontent.com/19245659/93582108-a4f7e280-f9bf-11ea-83f6-d1aaa9eb06da.jpg)

**Comment by thiesmoeller** [comment]
Please provide more information about your environment. 
OS. Camera model. Results of running the exact same use-case in exact same environment under pylon viewer.

**Comment by EngineerFSLT** [comment]
I would guess that it's MTU size related problem, was having that when it was on default MTU = 1500.
https://www.baslerweb.com/en/sales-support/knowledge-base/frequently-asked-questions/can-you-tell-me-how-to-optimize-network-parameters-when-i-m-using-the-basler-gige-vision-filter-driver-with-my-basler-gige-camera/14985/ this should help a bit in any other case, not entirely sure what might cause this.
