### ISSUE TITLE
Reading values from Camera

### ISSUE THREAD

**Issue by pmdbpc** [basler/pypylon#279]
I am unable to read the values in readable format in python. On running the sample/call.py code with some modifications, I get the output but I'm not sure as to how to convert the data in readable format.

Sample Code: 

> from pypylon import pylon
> 
> cam = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
> cam.Open()
> 
> print(cam.GainRaw)
> cam.GainRaw.Value = 3
> print(cam.GainRaw)
>
> cam.Close()
> print("done")

To this I'm getting an output as: 
`
<pypylon.genicam.IInteger; proxy of <Swig Object of type 'GENAPI_NAMESPACE::IInteger *' at 0x0000024CC5389450> >
<pypylon.genicam.IInteger; proxy of <Swig Object of type 'GENAPI_NAMESPACE::IInteger *' at 0x0000024CC5389450> >
done
`

I understand the data ("3") is written but I cannot know for sure what's being written and what was the original data before write operation. I'm not sure if I'm reading the swig object correctly.

I'm using pycharm IDE and have the swig path setup in environment variables.

**Comment by thiesmoeller** [comment]
`print(cam.GainRaw.Value)`

**Comment by TiernoGs** [comment]
Use `cam.GainRaw.GetValue()` and `cam.GainRaw.SetValue(3)` instead.

**Comment by pmdbpc** [comment]
Thanks for helping @thiesmoeller @TiernoGs.
