### ISSUE TITLE
Camera not running in Live mode using Tkinter canvas window.

### ISSUE THREAD

**Issue by pmdbpc** [basler/pypylon#288]
I'm building a simple `tkinter` window and working on running camera in single image capture and in live mode. I have been able to capture image snapshot but the live mode doesn't seem to be working. The `tkinter` window freezes and I have to kill the window every-time. 

However, when using the OnebyOne Grab strategy **without tkinter canvas**, the live stream works just fine.

Is the grab strategy used for live mode correct or should I used a different grab strategy?
The max buffer value is left at default setting?
Have tried out with 10000 and 5000 as timeout value during `RetrieveResult` but nothing changes in output.

I have used 2 cameras - acA1600-60gm and acA1920-40gc, both giving similar results. I have attached my code files for reference. 

Both are python files. Extension changed for uploading
[camTest.txt](https://github.com/basler/pypylon/files/5421921/camTest.txt)
[camTestWindow.txt](https://github.com/basler/pypylon/files/5421922/camTestWindow.txt)

**Comment by thiesmoeller** [comment]
Methods called from the gui alsways have to be short ... otherwise you lockup gui thread.

See attached small patch that gives you a live view 
.... just quick edit  as I don't really know tkinter ;-)

This is the pattern, that you should follow.


[live_view_sample.patch.txt](https://github.com/basler/pypylon/files/5425572/live_view_sample.patch.txt)

**Comment by pmdbpc** [comment]
@thiesmoeller thanks for the patch file. this really helped. The live mode started but it seems there are lot of frames getting dropped. They follow a pattern the no. of frames missed slowly reduce to none and then after a couple of seconds this pattern repeats

![ezgif com-gif-maker](https://user-images.githubusercontent.com/67097363/97001516-19d9b180-1556-11eb-8fdb-edc7a5bb3bf4.gif)

Is it related to the frame rate? or something else?

**Comment by thiesmoeller** [comment]
Maybe tkinter is queuing the updates to the image.
Try reducing camera framerate

**Comment by thiesmoeller** [comment]
https://solarianprogrammer.com/2018/04/21/python-opencv-show-video-tkinter-window/

**Comment by pmdbpc** [comment]
@thiesmoeller That worked I adjusted the frame rate to 10 and 98% video seems to appear good. although once in a while I do get a frame miss and see a white screen flash. I've added few more lines of code in start and stop live methods. Do you think removing these lines to another method should help here?

Also, while testing the start / stop live mode switching back to back -

sometimes (after starting / stopping live for more than 3-4 times) for start live the window gets crashed while executing:
`self.display_update_handler_hdl = self.vid.camera.RegisterImageEventHandler(self.display_update_handler, pylon.RegistrationMode_ReplaceAll, pylon.Cleanup_None)`

and for stop live, the window gets crashed while executing:
`self.vid.camera.DeregisterImageEventHandler(self.display_update_handler_hdl)`

I'm assuming the issue here is related to the handle registration / deregistration. I tried going through the code of pylon.py of pypylon, but couldn't figure out what's causing this.

**Comment by thiesmoeller** [comment]
any error messages?

**Comment by pmdbpc** [comment]
> any error messages?

None. 
The application window either hangs (Not Responding) or it crashes. I have put up my complete code on GitHub. 
Here is the link: [https://github.com/pmdbpc/OpenCV/tree/master/Basler%20Application](url)

The same behavior is observed when I stop camera in live mode & immediately capture an image or when I switch back to back between live mode as well. No issues when I capture back to back snapshots.

**Comment by thiesmoeller** [comment]
this triggers an issue with the event handling mechanism ... can be reproduced in reduced setup.
quick workaround for you is to set ( pylon.Cleanup_Delete instead of pylon.Cleanup_None ) -> this will memleak the swig director but should keep you going for now.

**Comment by pmdbpc** [comment]
@thiesmoeller - the application works much smoother now. Thanks.

**Comment by fatmafarah** [comment]
@pmdbpc can you please post your code?

**Comment by oumaymabelhajsalah96** [comment]
Hello @pmdbpc , can you help me, I work with a basler and tkinter camera like you.
I can contact you on gmail please,
my gmail is oumayma.belhajsalah96@gmail.com

**Comment by Lucrezia-Cester** [comment]
Is there a code for this live script now?
