### ISSUE TITLE
basler camera can not call by opencv3.4.9 in usb3.0 connect

### ISSUE THREAD

**Issue by lijinglin-star** [basler/pypylon#290]
I want to only use opencv3.4.9 (Dont't use pylon to capture and translate it to Mat format). My computer is windows 10 home version, and it was already installed pylon6.1 and opencv3.4.9. I created a project in vs2019 and writed following code. But it doesn't work. The log displays "Can not open the camera", but i can use opencv to call my local camera in my computer, only can't use the usb camera in usb3.0 connect.

//Initiate the camera初始化相机
	cv::VideoCapture cam(1);//select camera, (0) is local camera on desktop, (1) is usb camera (basler ac800-510um)
	if (!cam.isOpened())
	{
		std::cout << "Can not open the camera" << std::endl;
		cv::waitKey(1);
		return;
	}
	cam.set(cv::CAP_PROP_FRAME_HEIGHT, 600);
	cam.set(cv::CAP_PROP_FRAME_WIDTH, 800);
	//cam.set(CV_CAP_PROP_FPS, 10);
	cam.set(cv::CAP_PROP_BRIGHTNESS, -10);
	//cam.set(cv::CAP_PROP_EXPOSURE, -6);

**Comment by thiesmoeller** [comment]
your sample code is c++. this is the python bindings for pylon project.
In **python**, the GetArray method on the grabResult gives you a datastructure, that can be directly used by opencv
