### ISSUE TITLE
No binary for python 3.9

### ISSUE THREAD

**Issue by josselex** [basler/pypylon#307]
It would be good to have a binary releas on pypi for python 3.9.

**Comment by lars-ek** [comment]
I agree, I am also waiting...

**Comment by thiesmoeller** [comment]
I assume you work with a source build at the moment?

**Comment by josselex** [comment]
@thiesmoeller
No. I am holding back rollout of python 3.9 because of this,

**Comment by BlackbirdB51** [comment]
I'd like to have a release as well.
I tried to build it from source, but did not manage to do it. What Visual Studio packages do I need?
I resorted to install temporarily python 3.8 as well for that specific application.

**Comment by marv** [comment]
pypylon supports Python 3.9 now starting with 1.7.0 and you can find releases either here on GitHub or on PyPi 🥳

**Comment by BlackbirdB51** [comment]
Yes. Initially the builds for windows were missing, but with 1.7.1 they are present now. Thanks to the devs!
