### ISSUE TITLE
Basler Light Control Features

### ISSUE THREAD

**Issue by flschmid89** [basler/pypylon#309]
Are there functions to use the features from Basler Light Control or plannings on the roadmap to implement these?

[Basler Documentation Light Control Feature Set](https://docs.baslerweb.com/light-control-feature-set )

Example from c++ functions

`// Enable the light control mode
camera.BslLightControlMode.SetValue(BslLightControlMode_On);
//Enumerate the light devices
camera.BslLightControlEnumerateDevices.Execute();
//Select light device 1
camera.BslLightDeviceSelector.SetValue(BslLightDeviceSelector_Device1);
//Set the maximum current of device 1 to 100 mA
camera.BslLightDeviceMaxCurrent.SetValue(100.0);
//Set the brightness to 100 %
camera.BslLightDeviceBrightness.SetValue(100.0);
//Set the operation mode to continuous
camera.BslLightDeviceOperationMode.SetValue(BslLightDeviceOperationMode_On);`

**Comment by thiesmoeller** [comment]
Search and replace is all you need
Replace the enum constants by string versions

```python
#Enable the light control mode 

camera.BslLightControlMode.SetValue("On")

#Enumerate the light devices 

camera.BslLightControlEnumerateDevices.Execute()

#//Select light device 1 

camera.BslLightDeviceSelector.SetValue("Device1")

#//Set the maximum current of device 1 to 100 mA 

camera.BslLightDeviceMaxCurrent.SetValue(100.0)

#//Set the brightness to 100 % 

camera.BslLightDeviceBrightness.SetValue(100.0)

#//Set the operation mode to continuous 

camera.BslLightDeviceOperationMode.SetValue("On")
```
