### ISSUE TITLE
What is the code to change the frame rate?

### ISSUE THREAD

**Issue by egawatomoya** [basler/pypylon#316]
Gain and exposure time can be set in "calltest.py" in ".\pypylon\tests\pylon_tests\usb", but frame rate settings cannot be found. What file is it written in? Or what kind of code can I set?

**Comment by thiesmoeller** [comment]
pypylon gives you access to all features, that your camera has. 
Exactly as referenced in the manual.

https://docs.baslerweb.com/acquisition-frame-rate

the c++ code can really be converted by "search&replace"

so from a 
```c++
// Set the upper limit of the camera's frame rate to 30 fps
camera.AcquisitionFrameRateEnable.SetValue(true);
camera.AcquisitionFrameRate.SetValue(30.0);
```

you get:
```python
# Set the upper limit of the camera's frame rate to 30 fps
camera.AcquisitionFrameRateEnable.SetValue(True)
camera.AcquisitionFrameRate.SetValue(30.0)
```

Or in other words:
Configure your camera using pylon viewer. Learn about the parameters that you want to control.
Look up the documentation window in pylonviewer and you have your feature names :-)

![image](https://user-images.githubusercontent.com/5516325/104899375-100bf280-597b-11eb-9abf-8f5af1875153.png)

**Comment by kolupaev-hsw-de** [comment]
It doesn't work. Got an exception: "Node is not writable. : AccessException thrown in node 'AcquisitionFrameRateEnable' while calling 'AcquisitionFrameRateEnable.SetValue()' (file 'booleant.h', line 61)"

**Comment by thiesmoeller** [comment]
Perhaps missing to Open your camera before?

`camera.Open()`

**Comment by kolupaev-hsw-de** [comment]
@thiesmoeller, thank you, that helped.
