### ISSUE TITLE
How do I choose a released wheel? What does cp36 cp 37 etc. mean?

### ISSUE THREAD

**Issue by rafwaf** [basler/pypylon#323]
Hi perhaps this is a newbie question, but how do I decided which wheel to download?

linux vs win is pretty straight forward, but I'm not sure what the diferent cp36, cp37 etc... means, and also, I have not seen win64, only win-amd-64, yet I have an Intel CPU :)

Clearly I'm missing something here...

p.s. I already decided to use pip install pypylon to work around this, as I'm using Windows 10, so it works, but I figured others my benefit from an explanation for this, especially if running on a Linux version that doesn't currentl work with PyPi. Also, for my own curiosity... :)

Thanks in advance.

**Comment by thiesmoeller** [comment]
The naming scheme is described in this PEP
"PEP 425 -- Compatibility Tags for Built Distributions | Python.org" https://www.python.org/dev/peps/pep-0425/

The 64bit ISA of your intel cpu is a developed to be compatible to AMD's original spec. Thus amd64.
