### ISSUE TITLE
Attribute error:  module 'pypylon' has no attribute 'InstantCamera'

### ISSUE THREAD

**Issue by rcbullins** [basler/pypylon#342]
Hello,

I am using a basler camera to implement in deep lab cut live. 

However, when I try to initialize the camera with the following piece of code, "camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())", as is described in the [ README.md](https://github.com/basler/pypylon/blob/master/README.md#installation-from-source) I receive the following attribute error, "module 'pypylon' has no attribute 'InstantCamera'".

Is there a different version of InstantCamera with a different name for pypylon version 1.7.2? Or do I need to add it to my path differently?

Thank you!

**Comment by thiesmoeller** [comment]
`from pypylon import pylon`

So you import this way ?

Or are you in the source directory?

**Comment by rcbullins** [comment]
I have been importing using 'import pypylon as pylon'.

**Comment by thiesmoeller** [comment]
This will just rename pypylon to pylon.
https://docs.python.org/3/reference/simple_stmts.html

Pypylon has two sub modules pylon and genicam

You need the pylon sub module

**Comment by rcbullins** [comment]
Okay, it is importing now. Thank you!
