### ISSUE TITLE
Basler Aces2 USB Cam on Jetson Nano

### ISSUE THREAD

**Issue by kotai2003** [basler/pypylon#354]
Hi,
I am trying to install one basler aces2 usb camera on Nvidia's Jetson Nano.
Jetpack version is 4.5.

```Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypylon import pylon
>>> 
>>> camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kotai/.local/lib/python3.6/site-packages/pypylon/pylon.py", line 1582, in CreateFirstDevice
    return _pylon.TlFactory_CreateFirstDevice(self, *args)
_genicam.RuntimeException: No device is available or no device contains the provided device info properties. : RuntimeException thrown (file 'TlFactory.cpp', line 694)
```

I would like to know there is someone who have succeeded in installing pylon on Jetson Nano?
Please leave your advices. Thanks.

**Comment by thiesmoeller** [comment]
Is your device visible with `lsusb`?

**Comment by SMA2016a** [comment]
did you install pylon SDK and  setup the udev rules using pylon setup script? 
It is normaly located in:
 /opt/pylon/share/pylon/setup-usb.sh 

as already asked, you you post the output of lsusb,please?

**Comment by kotai2003** [comment]
@SMA2016a 
Sorry for late reply.

As you mentioned, I checked lsusb and re-install the pylon SDK. and I confirm that my basler cam works on Jetson Nano properly.

Thanks so much.
