### ISSUE TITLE
Setting the parameters of the sensor camera 

### ISSUE THREAD

**Issue by Jasurkhuja** [basler/pypylon#359]
Could not find the code for setting the Analog control parameters of the Basler camera, specifically the black level selector and Gamma through the pypylon. I am using the camera model: acA2500 -14uc.

**Comment by Jasurkhuja** [comment]
Dear all 

import cv2
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
camera.Open()

camera.BlackLevel.SetValue(15)

Issue solved

**Comment by thiesmoeller** [comment]
@Jasurkhuja please take a look at our companion repository https://github.com/basler/pypylon-samples

There we explain all basics and you could also watch a webinar about pypylon.
