### ISSUE TITLE
grapping images by triggering regardless of time

### ISSUE THREAD

**Issue by ridvanozdemir** [basler/pypylon#374]
how can i grap images by triggering regardless of time?

I get error when i wait
TimeoutException: Grab timed out. The acquisition is not started. : TimeoutException thrown (file 'instantcameraimpl.h', line 1056)

**Comment by thiesmoeller** [comment]
Please check the hardware triggering notebook in https://github.com/basler/pypylon-samples

Either using the background loop or using wait forever.

**Comment by ridvanozdemir** [comment]
thank you for fast answer

**Comment by ridvanozdemir** [comment]
I checked the example but it is about software trigger,
Do you have any for hardware trigger?

**Comment by thiesmoeller** [comment]
Take a look into our companion repository with more samples and notebooks that demonstrate most of pypylon features: https://github.com/basler/pypylon-samples
