### ISSUE TITLE
No devices can be found

### ISSUE THREAD

**Issue by keck-in-space** [basler/pypylon#379]
Hello,

I am trying to use the pypylon library to enumerate the devices that are connected via Ethernet. However, when I call the following code, the `tlFactory.EnumerateDevices()` call is an empty tuple and the line to create the device fails with an exception. I've copied the code and the result below. Pylon sees 10 cameras connected.

```
from pypylon import pylon
from pypylon import genicam

tlFactory = pylon.TlFactory.GetInstance()
devices = tlFactory.EnumerateDevices()
print(f"devices: {devices}")
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
```

```
devices: ()
Traceback (most recent call last):
  File "C:\python_issue.py", line 7, in <module>
    camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\pypylon\pylon.py", line 1582, in CreateFirstDevice
    return _pylon.TlFactory_CreateFirstDevice(self, *args)
_genicam.RuntimeException: No device is available or no device contains the provided device info properties. : RuntimeException thrown (file 'tlfactory.cpp', line 694)
```

Is there something else I need to do to let pypylon know that the devices are connected via Ethernet? The only way this code works is if I set an environment variable to run with emulated devices. No real devices are ever seen.

Thank you!

Environment Setup

Windows 10
Python 3.9.5
pypylon 1.7.2
![image](https://user-images.githubusercontent.com/32853381/122830324-2fa2a080-d2b6-11eb-9f16-2823289c9e53.png)

**Comment by Elektri4ker** [comment]
I have the same problem.
I've investigated it and can tell that `tlFactory.EnumerateDevices()` does not send broadcast discovery requests to '255.255.255.255'.
Here follows a picture of Wireshark dump while `tlFactory.EnumerateDevices()` was called. You see that it does broadcast only for a particular subnet (address 10.10.11.255)
![pypylon discovery](https://user-images.githubusercontent.com/8113198/124240076-acd1df00-db1a-11eb-9896-d9715eaf038d.png)

@keck-in-space So your code will work if you manually configure devices with Pylon to appropriate ips and subnets.

Here follows a picture of Wireshark dump while Pylon IP configurator was working.
![pypylon discovery](https://user-images.githubusercontent.com/8113198/124240558-21a51900-db1b-11eb-93f5-6691a119617b.png)

Is there a way to discover cameras with 255.255.255.255 broadcast, as Pylon does it?

**Comment by thiesmoeller** [comment]
see here [gige ip config samples](https://github.com/basler/pypylon/blob/master/samples/gige_ip_config.py)

**Comment by Elektri4ker** [comment]
> see here [gige ip config samples](https://github.com/basler/pypylon/blob/master/samples/gige_ip_config.py)
> 
> .. overall your camera should be in the same subnet as your host,
> to simplify the the whole setup.

Yes, I'm using this example. After calling`tlFactory.EnumerateDevices()` it ends up with "no GigE device found".

But can I somehow configure any connected device, even if it is not configured yet? Just like "Pylon IP configurator" does it via broadcast.

**Comment by MattsProjects** [comment]
Yes, use Enumerate**All**Devices()
This is what the IPConfigurator uses.

**Comment by milancurcic** [comment]
Same problem here. I have a GigE camera (acA2500-20gm) configured on the same subnet as the host. I can connect to it from Pylon Viewer, and I can ping it from the command line. However, ` tl_factory.EnumerateDevices()` keeps returning an empty tuple. 

@thiesmoeller, how do you recommend to best diagnose this? I'm using the pypylon from the latest commit on the master branch.

Thank you!

**Comment by milancurcic** [comment]
FWIW what works for me is to not rely on `EnumerateDevices` but to connect to the camera directly via its IP address:

```python
tlf = pylon.TlFactory.GetInstance()
tl = tlf.CreateTl('BaslerGigE')
cam_info = tl.CreateDeviceInfo()
cam_info.SetIpAddress('192.168.2.100')
cam = pylon.InstantCamera(tlf.CreateDevice(cam_info))
```

**Comment by thiesmoeller** [comment]
Make sure that the netmasks of the cameras really match the netmasks of your hosts Ethernet port.
Otherwise they won't react on the broadcast messages send out during enumeration.

**Comment by thiesmoeller** [comment]
Hi @ghazalehtrb,

Please describe your setup:
Operation system and how your camera is connected.

What did you configure how the camera should get its IP address?

What is "the software" that works?

**Comment by ghazalehtrb** [comment]
> Hi @ghazalehtrb,
> 
> Please describe your setup: Operation system and how your camera is connected.
> 
> What did you configure how the camera should get its IP address?
> 
> What is "the software" that works?

Thank you for your response @thiesmoeller ,
I have a Basler a2A1920-51gcPRO camera connected to an ethernet switch. My PC is also connected to the same switch. the operating system is Ubuntu 20.04. I am able to record with the pylon viewer software, but not with the pypylon api. when I try to configure the IP address with gige_ip_config.py I get the following error:

```
Traceback (most recent call last):
  File "gige_ip_config.py", line 38, in <module>
    raise EnvironmentError("no GigE device found")
OSError: no GigE device found
```
I have tried putting the camera on the same subnet with the pylon IP configurator but it doesn't change the error. 
I was able to make it work by playing around with the pylon IP configurator yesterday but I don't know how exactly. I keep having these issues every time I connect the camera to the switch and I don't know what the exact solution is.  

currently, this is the setup in the pylon IP configurator. I am able to record with the camera from the Pylon viewer software with this setup. However, the subnet mask of the camera (255.255.0.0) is different than the one shown for my PC ethernet connection (255.255.255.0). 
![image](https://user-images.githubusercontent.com/43464003/177604135-98782efd-ac05-440c-a910-f0e18f392428.png)

When I force it to be on the same subnet, it says the camera is unreachable, and I get the same error with the gige_ip_config.py .

![image](https://user-images.githubusercontent.com/43464003/177604731-602fb32c-5a0c-4cdc-a4e4-fabcdbd39e65.png)

could you please help me out with understanding the issue, I'm not very familiar with these concepts. 
Thanks

**Comment by thiesmoeller** [comment]
Hi @ghazalehtrb, 

in the setup you describe it shouldn't be required to use this special procedure to open a camera by it's IP address.
Or has your PC multiple network interfaces which run in LLA mode?  ( LLA == network 169.254.x.x)

Have you followed the documentation for installing on gige?
https://docs.baslerweb.com/network-configuration-(gige-cameras)

**Comment by SMA2016a** [comment]
<your PC multiple network interfaces which run in LLA mode>  it is not allowed to run multiple camera is LLA Mode. Since all network devices will be in the same network,

**Comment by swanandkAC** [comment]
> FWIW what works for me is to not rely on `EnumerateDevices` but to connect to the camera directly via its IP address:
> 
> ```python
> tlf = pylon.TlFactory.GetInstance()
> tl = tlf.CreateTl('BaslerGigE')
> cam_info = tl.CreateDeviceInfo()
> cam_info.SetIpAddress('192.168.2.100')
> cam = pylon.InstantCamera(tlf.CreateDevice(cam_info))
> ```

Thanks for the answer but after setting the IP and creating cam object, how do you read frames? I tried

```
def read(self):
        grabResult = cam.GrabOne(1000, pylon.TimeoutHandling_ThrowException)
        if grabResult.GrabSucceeded():
            img = grabResult.Array
            grabResult.Release()
            return img
```
But this gives an error saying

_genicam.TimeoutException: Grab timed out. : TimeoutException thrown (file 'InstantCameraImpl.h', line 1361)

Can u pls help me out?
