### ISSUE TITLE
Reset camera features to factory settings

### ISSUE THREAD

**Issue by batrlatom** [basler/pypylon#380]
Hello. Is it possible to reset features to some default state?

**Comment by thiesmoeller** [comment]
https://docs.baslerweb.com/user-sets.html

And see also the in depth examples at
https://github.com/basler/pypylon-samples
There we also reset the cameras to default config...

**Comment by thiesmoeller** [comment]
Not the samples folder in this repo but the pypylon-samples repo that I referenced in my last comment.

**Comment by batrlatom** [comment]
I have found it at https://github.com/basler/pypylon-samples/blob/main/notebooks/grabstrategies.ipynb . Thanks!

**Comment by Mahdiekteshafi** [comment]
Hello, my camera is Basler acA2500 14um, but the resolution settings are manipulated and it shows 1920*1080 and I cannot set the resolution to its standard mode of 2592*1944.

**Comment by thiesmoeller** [comment]
Please check the answer here https://github.com/basler/pypylon/issues/380#issuecomment-866079211

**Comment by SMA2016a** [comment]
Set offsetx and offsetY to minimum then try to set the width and height
