### ISSUE TITLE
How do you set the exposure to auto?

### ISSUE THREAD

**Issue by skyrapter86245** [basler/pypylon#385]
My camera: a2A1920-160ucBAS
https://docs.baslerweb.com/exposure-auto
I was reading through this, and attempting to apply the C++ code in pypylon, but maybe there's some kind of syntax difference?
Any help appreciated, thank you!

**Comment by thiesmoeller** [comment]
`cam.ExposureAuto = "Continuous"`

Take a look into our companion repository 

https://github.com/basler/pypylon-samples

To learn about the differences

**Comment by skyrapter86245** [comment]
Thank you!
