### ISSUE TITLE
seems it doesn't work on Windows 11？

### ISSUE THREAD

**Issue by mashuai191** [basler/pypylon#388]
hi guys, just to check with you that is the latest version by far support windows 11? i run my programe on win11 but stuck on the RetrieveResult call. Then i check with Wireshark tool to see that there is data from camera to my computer but seems my computer don't see the data so finally RetrieveResult call timeout.

**Comment by SMA2016a** [comment]
- does the camera work in pylon viewer?
-  did you disabled the firewall if you use a GigE camera?
- try to set the driver to socket driver. camera.StreamGrabber.Type = 'SocketDriver'

**Comment by mashuai191** [comment]
@SMA2016a after disable firewall as per your guide now i can make it through. thanks a lot!
