### ISSUE TITLE
Cannot install pypylon on RPi.

### ISSUE THREAD

**Issue by Ilias9807** [basler/pypylon#394]
I am trying to install the `pypylon` python wrapper for the pylon camera suite in my Raspberry pi 3 using `pip3` but I receive thre following error: 

![2021-07-30-155750_1364x768_scrot](https://user-images.githubusercontent.com/74251741/127656299-100451a8-840b-4bbf-adc7-fb52daca0122.png)

My RPi runs on ARM Linux 32bit, I am using python 3.7.3 and I have the pylon camera suite 6.2.0 installed.
I also tried buliding it from source following the directions you provided but with no luck.

Any help would be much appreciated.

**Comment by jackcary** [comment]
`pip3 install --upgrade pip`

**Comment by Ilias9807** [comment]
@jackcary Thank you for the response. My pip is up to date with the latest version, and I already run an `install upgrade` just in case, but got nowhere. Regarding the rest of your suggestions I 'll try them out and get back to you.

**Comment by jackcary** [comment]
@Ilias9807 I also had better luck when I specified the exact wheel file for pip to install.  In your case (32-bit ARM) that may be pypylon-1.7.2-cp37-cp37m-manylinux_2_24_armv7l.whl

`pip3 install https://github.com/basler/pypylon/releases/download/1.7.2/pypylon-1.7.2-cp37-cp37m-manylinux_2_24_armv7l.whl`

**Comment by SMA2016a** [comment]
<My pip is up to date with the latest version>
waht pip version are you  using?

**Comment by Ilias9807** [comment]
> waht pip version are you using?

@SMA2016a Uppon checking the pip version on my system is 20.3.4, so not the very last published version.

**Comment by Ilias9807** [comment]
UPDATE: Apparently my pip3 version was quite outdated, (version 18.x.x), so running an update like so:

`sudo -H pip3 install --upgrade pip`

Did the trick.
