### ISSUE TITLE
Activating Automatic Image Adjustment using pypylon 

### ISSUE THREAD

**Issue by LucasVandroux** [basler/pypylon#4]
Hello,
I really like the `Automatic Image Adjustment` feature from the Pylon Viewer:

![auto_image_adjustment](https://user-images.githubusercontent.com/1956886/40846222-48460e46-65b9-11e8-873f-3c131be1a44d.png)

Is there a way to activate the same feature directly from pypylon? I looked quickly in the examples but I didn't find anything.

Thanks a lot for your time,

- Lucas

**Comment by basler-oss** [comment]
@LucasVandroux: This function is currently not available in our APIs. We have individual API calls for activating auto brightness, auto white ballance auto gain. You might use these functions instead.

**Comment by paaraujo** [comment]
Dear @basler-oss , I am starting with the pypylon, how can I activate the auto brightness, auto white ballance and auto gain parameters?

**Comment by weberhen** [comment]
@paaraujo 

camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreatteFirstDevice())
camera.Open()
camera.GainAuto.SetValue("Once") sets the auto gain for example. 

To have a list of all parameters you can change #40
