### ISSUE TITLE
Simultaneous capturing on two acA1300-30gc cameras

### ISSUE THREAD

**Issue by kimdonggyun** [basler/pypylon#430]
I am using two GigE cameras for an experiment but still I haven't found best solution to take simultaneous video capture with two separate cameras.

I'm using below code to capture the video from one camera.

```
    with get_writer("/Users/dkim/Desktop/basler_camera/recording/ffmpeg_demo.avi") as writer:
        cam.StopGrabbing()
        cam.StartGrabbingMax(300)
        while cam.IsGrabbing():
            res = cam.RetrieveResult(300)
            writer.append_data(res.Array)
            print(res.BlockID)
            res.Release()
```

I tried to find a function on pypylon but I couldn't find anything to support simultaneous video capuring.

Is there a certain way to trigger two cameras at the same time by using software trigger (of course, there will be some latency)
Or hardware trigger is the only way to do it? (even it's possible to set up hardware trigger with basler cameras?)

**Comment by thiesmoeller** [comment]
And check this sample
https://github.com/basler/pypylon/blob/master/samples/gige_action_command.py

**Comment by kimdonggyun** [comment]
> And check this sample
> https://github.com/basler/pypylon/blob/master/samples/gige_action_command.py

What's the difference between
```
cam = pylon.InstantCamera()
cam = pylon.InstantCameraArray()
```
?

To handle multiple cameras, which one should I use to put all connected cameras in "cam"?

**Comment by thiesmoeller** [comment]
We provide a companion repository https://github.com/basler/pypylon-samples
With advanced samples.

There is a multi camera sample provided.

InstantCameraArray is just a wrapper class to make handling multiple cameras easier.

**Comment by kimdonggyun** [comment]
> And check this sample
> https://github.com/basler/pypylon/blob/master/samples/gige_action_command.py

I've followed this script and it's working until setting the multiple cameras in a group and changing the parameters of the cameras.

My code is so far:
```
# 1. get transport layer and all attached devices
tl_factory = pylon.TlFactory.GetInstance()
set_devices = tl_factory.EnumerateDevices() #enumerate devices connected

# 2. check the devices information
cams = None
if len(set_devices) == 0:
    raise pylon.RuntimeException("No camera connected")
else:
    print("total number of devices:", len(set_devices)) # print total number of devices connected
    for dev_info in set_devices: # 
        if dev_info.GetDeviceClass() == 'BaslerGigE': # check if the connected cameras are GigE model. Otherwise software trigger won't work
            print("using %s as IP %s" % (dev_info.GetModelName(), dev_info.GetIpAddress()))
            cams = pylon.InstantCamera(tl_factory.CreateDevice(dev_info)) # create instant of connected cameras
            break
    else:
        raise EnvironmentError("no GigE device found")

# setring camera's parameters
fps = 10 # frame per sec
ExposureTime = 5000 # in µs
Height, width = 962, 1286 # in pixel

cams.Open() # open camera to change the parameter
print("Setting device ", cams.GetDeviceInfo().GetFriendlyName())
cams.Height.SetValue(Height)
cams.Width.SetValue(width)
cams.ExposureTimeRaw.SetValue(ExposureTime)
cams.AcquisitionFrameRateAbs.SetValue(fps)
print(cams.Height.GetValue(), cams.Width.GetValue(), cams.ExposureTimeRaw.GetValue(), cams.AcquisitionFrameRateAbs.GetValue())

cams.Close() # close camera


# 1. set action key, group key and group mask. As I'm using one group and all cameras in this group working simaltaneously,
# I did not set multiple action key, group key and group mask
action_key = 0x4711
group_key = 0x112233
group_mask = pylon.AllGroupMask

# 2. Initiate automatic configuration by registering ActionTriggerConfiguration.

cams.RegisterConfiguration(
    pylon.ActionTriggerConfiguration(action_key, group_key, group_mask),
    pylon.RegistrationMode_Append,
    pylon.Cleanup_Delete
    )

# 3. Create a suitable ActionCommand object. For that a GigETransportLayer object is needed.
gige_tl = tl_factory.CreateTl('BaslerGigE')

# 4. Using default value of "255.255.255.255" for fourth parameter 'broadcastAddress'.
act_cmd = gige_tl.ActionCommand(action_key, group_key, group_mask)
```

It's working until here.

Now what I want to do is recording videos from two cameras and saving them in separate video files.
I just tried with one camera with below code:

```
# capturing video with multiple cameras at simultaneously
with get_writer("/Users/dkim/Desktop/basler_camera/recording/multi_cams.avi") as writer:
    cams.StopGrabbing()
    cams.StartGrabbingMax(300) <- error message appeared here
    while cams.IsGrabbing():
        res = cams.RetrieveResult(300)
        writer.append_data(res.Array)
        #print(res.BlockID)
        res.Release()
```

But it gave error message:

`RuntimeException: Could not apply configuration. Pylon::GenericException caught in OnOpened method msg=Device doesn't support action commands. The ActionCommand features are not writable. : RuntimeException thrown (file 'ActionTriggerConfiguration.h', line 124) : RuntimeException thrown (file 'ActionTriggerConfiguration.h', line 212)`

Any idea how to solve this issue?

**Comment by SMA2016a** [comment]
please check with pylon viewer, if the entry "action" is in the TriggerSource node.
if not, turn to your local camera distributer to get a firmware update for your cameras.

**Comment by SMA2016a** [comment]
maybe the camera be open while you are trying to write the camera parameter

**Comment by kimdonggyun** [comment]
> maybe the camera be open while you are trying to write the camera parameter

But I closed the camera after I open the cam.

```
cams.Open() # open camera to change the parameter
print("Setting device ", cams.GetDeviceInfo().GetFriendlyName())
cams.Height.SetValue(Height)
cams.Width.SetValue(width)
cams.ExposureTimeRaw.SetValue(ExposureTime)
cams.AcquisitionFrameRateAbs.SetValue(fps)
print(cams.Height.GetValue(), cams.Width.GetValue(), cams.ExposureTimeRaw.GetValue(), cams.AcquisitionFrameRateAbs.GetValue())

cams.Close() # close camera <-------- here
```

**Comment by kimdonggyun** [comment]
> please check with pylon viewer, if the entry "action" is in the TriggerSource node.
> if not, turn to your local camera distributer to get a firmware update for your cameras.

Alright, Now I've checked pylon viewer and there, Acquisition Controls > Trigger Source.
In that section, "Trigger Software" and "Line1" are. But no "action". In this case what should I do?
And maybe can I solve this issue by adjusting "Trigger Mode" to "On"?

**Comment by kimdonggyun** [comment]
Alright it turns out my camera model does not support "Action Commands".
Can I use "Trigger Software" instead?

**Comment by thiesmoeller** [comment]
Have you checked with your local distributor about a firmware update?

**Comment by kimdonggyun** [comment]
> Have you checked with your local distributor about a firmware update?

No, I haven't done it yet. Rather I'm moving on to python's multiprocessing method
