### ISSUE TITLE
TimeoutException When using grab

### ISSUE THREAD

**Issue by trungpt2608** [basler/pypylon#452]
Hi everyone, I am having some problem when using grab in python. I can see the camera is working  from the pylon viewer .I use Basler 2500-14gc

here is my code:
from pypylon import pylon
import cv2
from pypylon import genicam
import sys
import time

camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())

camera.Open()
camera.GainRaw.Value = 25
camera.Width.SetValue(1300)
camera.Height.SetValue(1300)
camera.ExposureTimeAbs.SetValue(40015)
camera.PixelFormat = "BayerGB8"

camera.StartGrabbing(pylon.GrabStrategy_LatestImageOnly) 

converter = pylon.ImageFormatConverter()

converter.OutputPixelFormat = pylon.PixelType_BGR8packed
converter.OutputBitAlignment = pylon.OutputBitAlignment_MsbAligned
print(camera.PixelFormat.Symbolics)
n=0
def resize(img,x):
    scale_percent =float(x/img.shape[1])
    w = int(img.shape[1] * scale_percent)
    h = int(img.shape[0] * scale_percent)
    img = cv2.resize(src=img, dsize=(w,h))
    return img
while camera.IsGrabbing():
    grabResult = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
    if grabResult.GrabSucceeded():
        st=time.time()
        # Access the image data
        image = converter.Convert(grabResult)
        img = image.GetArray()
        img=resize(img,700)
        cv2.imshow('title', img)
        stop=time.time()
        print(str(stop-st))
  
camera.StopGrabbing()
cv2.destroyAllWindows()

when running:
Traceback (most recent call last):
  File "pylon.py", line 44, in <module>
    grabResult = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)
  File "C:\Users\PC\anaconda3\lib\site-packages\pypylon\pylon.py", line 3486, in RetrieveResult
    return _pylon.InstantCamera_RetrieveResult(self, *args)
_genicam.TimeoutException: Grab timed out. Possible reasons are: The image transport from the camera device is not working properly, e.g., all GigE network packets for streaming are dropped; The camera uses explicit triggering (see TriggerSelector for more information) and has not been triggered; Single frame acquisition mode is used and one frame has already been acquired; The acquisition has not been started or has been stopped. : TimeoutException thrown (file 'instantcameraimpl.h', line 1037)

**Comment by Lucrezia-Cester** [comment]
I have the same error @trungpt2608, did you ever find a solution?
