### ISSUE TITLE
Illegal instruction error upon import

### ISSUE THREAD

**Issue by Terizian** [basler/pypylon#475]
I've been trying to install pypylon from source on Ubuntu 18.04 with an ARM processor. 

I followed the steps of the README file:
- Compiler: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
- Python development files: python-dev/bionic,now 2.7.15~rc1-1 arm64 [installed]
- Swig: SWIG Version 4.1.0
- pylon from the debian package available on the basler website

I have a virtualenv set up for my python environment and I'm using 3.6.9
When I try to import the library to try some of the samples, I get the following error message: 
```
>>> from pypylon import pylon
Illegal instruction (core dumped)
```

**Comment by SMA2016a** [comment]
would you try run you app with sudo?

**Comment by Terizian** [comment]
It turned out to be caused by the numpy library installed. I had to downgrade to 1.19.3 for it to work.

**Comment by SMA2016a** [comment]
@Terizian  : Thanks for the update, then change the status to closed.

**Comment by thiesmoeller** [comment]
For reference:

This is the numpy openblas cpu detection issue https://github.com/numpy/numpy/issues/18131

and can be fixed by either up/down grading or setting the environment variable `OPENBLAS_CORETYPE=ARMV8`
