### ISSUE TITLE
Save Video From Previous Few Seconds Of Frames

### ISSUE THREAD

**Issue by unitedsoftworks** [basler/pypylon#476]
Hello,

I am trying to use the Basler instant camera to keep a buffer full of frames (lets say 1000 frames at 100 fps, so 10 seconds), and then when a certain event occurs in other parts of the code, I would like to read back this previous 10 second buffer into an MP4 file. the only issue is that I cant quite find where to access the images that already exist in the buffer, or even where to specify the buffer size. I don't want to grab. 

My first attempt was to grab the images as they come in and create a buffer in python itself, but there appears to be a way to do this in the pylon api, I just can seem to find it. 

Has anyone done something similar to this? Is it even possible?

**Comment by SMA2016a** [comment]
yes, this is possible.  You need set the parameter Maxbuffer to 1200 e.g

camera.MaxNumBuffer = 1200
if you call 

grabResult = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)

you need to keep all grabresult in your own list to prevent pylon overrwrite the frame buffer.

**Comment by unitedsoftworks** [comment]
thank you for the reply.

i guess the thing that is confusing me is, where do i access the 1200
frames in the buffer?

i can user RetrieveResult to get a frame, but does this come from that
buffer? and then how would i get the next frames from the buffer?

Thanks so much!

**Comment by unitedsoftworks** [comment]
okay so i actually got that working. but the issue we're having is this.

lets say i want to get the last 5 seconds of video from the buffer.

when i set my camera to 100fps, set maxnumbuffer to 500.

run startgrabbing

then i record a countdown timer for 10 seconds.

when i start retrieving the images from the buffer it shows me the first 5
seconds of the count down rather than the last 5.
so the video printed shows (10,9,8,7,6) rather than (5,4,3,2,1)

is there a way to make these cameras continuously replace the old frames in
the buffer?

**Comment by SMA2016a** [comment]
please refer to this
https://www.guru99.com/python-queue-example.html

**Comment by unitedsoftworks** [comment]
Thank you for the reply.
Right. so I had tried the approach with using my own list in python first in first out. 
but im wanting to get the frames from the buffer within the camera object itself. 
when i used a queue before, the grabResult pointers had already been destructed by pylons sdk before i could ever use them.

**Comment by SMA2016a** [comment]
if grabResult.GrabSucceeded():
            # Access the image data.
            print("SizeX: ", grabResult.Width)
            print("SizeY: ", grabResult.Height)
            img = grabResult.Array
            print("Gray value of first pixel: ", img[0, 0])
        else:
            print("Error: ", grabResult.ErrorCode, grabResult.ErrorDescription)
        grabResult.Release()


the array is buffer

 img = grabResult.Array

**Comment by RealBrandonChen** [comment]
Any method to retrieve all the latest buffers and save them as a 3D array instead of only one buffer frame? This is quite necessary when synchronized with other equipment.
