### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by pfilz0** [basler/pypylon#48]
The attribute 'GetDescription' is not present for all exceptions handled by genicam. E. g. when trying to grab an image while the camera is controlled by another application, a RuntimeException is thrown. If handled as in the samples via:
```python
except genicam.GenericException as e: 
    print("An exception occurred. ", e.GetDescription())`
```
, python throws an AttributeException

**Comment by campanelli-resonon** [comment]
I think I've hit this too and have resorted to using `str(e)` in general.

**Comment by pfilz0** [comment]
True, that would work. But it would still be nice if the args attribute were copied to GetDescription()

**Comment by thiesmoeller** [comment]
@pfilz0 @campanelli-resonon : will close this is issue as it seems to be solved. For any enhancement you made, please send a pull request with the changes
