### ISSUE TITLE
Bandwidth errors on Raspberry Pi

### ISSUE THREAD

**Issue by jveitchmichaelis** [basler/pypylon#49]
I'm running PyPylon on a Pi 3B+. I can capture images using the basic `grab.py` example, however if I plug another camera in and acquire, I'm no longer able to capture images. For example if I run this script:

```
import cv2
import time

cap = cv2.VideoCapture(0 + cv2.CAP_V4L2)

_, _ = cap.read()
time.sleep(10)
```

Even after the other camera has finished capturing (i.e. I wait for the delay), I get:

```
pi@raspberrypi:~/pypylon/samples $ python3 grab.py
Using device  daA1600-60uc
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
Error:  3791651083 The image stream is out of sync.
```

I've also seen payload discarded errors. It's definitely not the same camera, because the Dart doesn't enumerate as a V4L device. Is there some configuration I can change? Could this be due to an undervoltage condition on the Pi or something to that effect?

The script works perfectly well when run on its own.

**Comment by jveitchmichaelis** [comment]
Hi Thies,

Yep it's a UVC camera. I assume that opencv must be reading in a stream
continuously, even if you don't call "read". Though it's only a 16-bit VGA
camera so it shouldn't be saturating the bandwidth. I don't think there's
an obvious way of bandwidth limiting in opencv. It's using the V4L backend
so perhaps there's a better capture library to use.

Depending on the latency involved with releasing the uvc camera, I could
probably alternate capture between the two.

Thanks!

**Comment by jveitchmichaelis** [comment]
Thanks - that makes a bit more sense. The UVC camera is pulling 60fps, which is around 320mbps. I'll see if I can halve that and run the Dart with what's left over.

**Comment by Thyagutamizhan** [comment]
hi bro,
   lemme know how did you installe the pypylon package in raspberry pi 3b+?

**Comment by jveitchmichaelis** [comment]
@Thyagutamizhan just use the arm 32 bit hard float package from here (either the deb file or the tarball).

https://www.baslerweb.com/en/sales-support/downloads/software-downloads/#type=pylonsoftware;version=all;os=linuxarm

The deb installer is easiest "sudo dpkg -I pylon*.deb"

**Comment by charlie-plenty** [comment]
@Thyagutamizhan Did you manage to get everything up and running okay from within a Docker container?

**Comment by jveitchmichaelis** [comment]
Late reply, but yes I did in the end. It works quite well, I just limited the Dart bandwidth to 10MB/s which let me capture at full speed from the other camera and also save to an external USB stick.
