### ISSUE TITLE
Save images in array

### ISSUE THREAD

**Issue by visionbyalex** [basler/pypylon#492]
Hello everybody!

I have a basler acA5472-17uc combined with a linear stage in order to acquire images depending on a trigger signal from the stage. Is there a efficient way to save the captured images in an array and read it out later? This is necessary because the stage triggers every 100 ms and my system runs on a RPI, so resources are limited. 

I saw the following issue : https://github.com/basler/pypylon/issues/466
Following a code snippet from the mentioned issue:

```
for m in range(n):
    with cam.RetrieveResult(2000) as res:
        t1 = time.time()

        buf = BytesIO()
        Image.fromarray(res.Array).save(buf, 'tiff')
        now = datetime.utcnow()
        filename = 'img_' + now.strftime('%Y%m%d_%H%M%S.%f.tif')
        open(output_path + filename, 'wb').write(buf.getbuffer())

        t2 = time.time()
        print('fps: %.2f' % (1 / (t2 - t1)), \
              'bandwidth: %.2f MB/s' % (image_size / 1024**2 / (t2 - t1)))

cam.StopGrabbing()
cam.Close()

```
Here a loop iterates capturing and saving the images, but in my case I want to capture the images during e.g. a loop in an array/buffer/or something similar and save/process the images after finishing the loop. I am trying to get something like that:

```
for m in range(n):
    with cam.RetrieveResult(2000) as res:
        buffer[m] = img.AttachGrabResultBuffer(res)
        
for x in range(n):        
    buffer[x].Save( pylon.ImageFileFormat_Tiff, output_path + 'test.tif' )

cam.StopGrabbing()
cam.Close()
```

The previous code is not working, it is just an example of an idea how it should work like.

Has anybody an idea how to solve this problem?
Thx a lot!

**Comment by thiesmoeller** [comment]
You have to do some system analysis:

* your camera has 20mpix and thus generates ~20MB/frame in bayer8 -> 40MB/frame in YUV422 -> 60MB/frame in RGB
* frame period 100ms -> Datarates ~200MB/s in bayer8 -> 400MB/s in YUV422 ( slighty too much for USB3 ) -> 600MB/s in RGB ( not working )

It is not possible to write or encode this datarate 
a) to sd-card on RPi (https://www.pidramble.com/wiki/benchmarks/microsd-cards#4-model-b) or  to EMMC
b) the video encoder on RPi is not capable to do HW accelerated encoding of 20MPix image

The only options I see are:
a) move to use a SSD e.g. on a Raspberry CM4 NVMe SSD >= 200MB/s linear write performance ( e.g. https://pibenchmarks.com/benchmark/56050 )
b) limit the number of frames and store the data in memory.
    e.g. choose 8GB Model and hold the video data in a python array or in a 3d ndarray and write it to disc in background slow speed.
