### ISSUE TITLE
no released binary file in the link

### ISSUE THREAD

**Issue by alwynchen123** [basler/pypylon#5]
Hi,

I didn't find the compiled wheel file in the link. I guess the readme.md is not updated?

Thanks,

Alwyn

**Comment by basler-oss** [comment]
That's true. We temporarily removed the binaries as a bug needs to be fixed (see [issue #1](https://github.com/basler/pypylon/issues/1)). We put them back in the next days.

**Comment by MonkeyKH** [comment]
Do you Have a Presumed time scale for when you want to add the binaries again? 
thanks

**Comment by stefanklug** [comment]
@MonkeyKH We are currently working on automating the binary releases. First release candidates are currently flowing into the releases page. Feel free to test them. I expect the final release to be ready next week.

**Comment by MonkeyKH** [comment]
Thanks a lot For all of your guys hard work, i will definetly do that.
