### ISSUE TITLE
Pypylon connot import name _pylon

### ISSUE THREAD

**Issue by sulaimansiddiqi233** [basler/pypylon#514]
Hello to every one .
I am using Basler Camera in my project is is working in pycharm and I create the bat file it is working also there. but the problem is that I want to convert my code from .py to .exe then I get the error. as you can see in attachment file. could help me out. thank you.
I am using window system. 64 bit . python 3.8 65 bit and pypylon 1.8.0 version
![Screenshot (10) png2](https://user-images.githubusercontent.com/41513015/178100954-a4310096-692c-4e4e-99b7-88eff38e7a81.png)

**Comment by thiesmoeller** [comment]
What version of pyinstaller do you use ?

**Comment by sulaimansiddiqi233** [comment]
pyinstaller 5.2

**Comment by thiesmoeller** [comment]
Can reproduce. 
It is longer time ago, that I tested pyinstaller on windows.
The pypylon hook ( part of pyinstaller ) should normally take care to collect all required libraries.
Why this is broken now with the very current pyinstaller 5.2 version has to be checked....
As we haven't changed the library layout for windows

**Comment by sulaimansiddiqi233** [comment]
in which version of pyinstaller it works correctly . I will try that one

**Comment by thiesmoeller** [comment]
As one check:
Are you calling pyinstaller from a virtualenv?

**Comment by sulaimansiddiqi233** [comment]
no my code is in pycharm and it is connected with python I am call the pyinstaller directly from cmd with all libraries .

**Comment by thiesmoeller** [comment]
With "ran your code" you mean that you used above code as the patched pyinstaller hook file?

**Comment by thiesmoeller** [comment]
But you show the output of the python console....

Not the terminal ...

How do you call pyinstaller?

**Comment by sulaimansiddiqi233** [comment]
İn cmd : pyinstaller code.py

**Comment by thiesmoeller** [comment]
Save my above code into a file hook-pypylon.py in a directory .\hooks

`pyinstaller --additional-hook-dir .\hooks  <your_main_script.py>`

This way you override the buggy hook file of pyinstaller

**Comment by sulaimansiddiqi233** [comment]
I added the code but it given the below error/ Sent from Mail for Windows From: Thies MöllerSent: Monday, July 11, 2022 7:13 PMTo: basler/pypylonCc: sulaimansiddiqi233; AuthorSubject: Re: [basler/pypylon] Pypylon connot import name _pylon (Issue #514) Save my above code into a file hook-pypylon.py in a directory .\hookspyinstaller --additional-hook-dir .\hooks <your_main_script.py>This way you override the buggy hook file of pyinstaller—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by thiesmoeller** [comment]
Could you please comment from the webinterface. Mail replies are unreadable

**Comment by sulaimansiddiqi233** [comment]
i added the code after i run the . i got the error
![Screenshot 2022-07-11 191919](https://user-images.githubusercontent.com/41513015/178321279-5aeb59c2-1a9b-4064-8ede-f49b6eb0bfc5.png)

**Comment by thiesmoeller** [comment]
Sorry typo...

--additional-hooks-dir ....

**Comment by sulaimansiddiqi233** [comment]
It works Sir . thanks a lot.
