### ISSUE TITLE
How to acquire at high fps?

### ISSUE THREAD

**Issue by Lucrezia-Cester** [basler/pypylon#531]
Hello, 

I am trying to acquire images at 500 fps. When using the Pylon Software I managed to do this by simply reducing the number of pixels that are recording and increasing fps. 

How can I do the same thing with python? 

I am using the grab.py example.

Can I just add for the fps sopmething like  camera.ExposureTime.SetValue(100)?

This somewhat increases the fps, but what about the code to reduce the number of acquiring pixels, so that only a small subset of pixels acquires data? In the pyon software this can be changed by changing the ROI which reduces the number of active pixels.

Also, how can I display fps the same way the software does, so I know what parameter of fps it is acquiring at?

**Comment by Lucrezia-Cester** [comment]
UPDATE: 

just used the features Height and Width to crop ROI. 

One more question tho, how can I check fps?

**Comment by thiesmoeller** [comment]
https://docs.baslerweb.com/resulting-frame-rate#checking-the-resulting-frame-rate
