### ISSUE TITLE
Enable to activate ChunkMode

### ISSUE THREAD

**Issue by s-kesh** [basler/pypylon#537]
Thanks for writing this wonderful library.

I am trying to save metadata with each image using ChunkMode. While my camera **acA1920-155um** support Chunk Mode according to [Feature page on Basler's website] (https://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace/aca1920-155um/#features), when I try to enable Chunk Mode genicam gives me an error "LogicalErrorException: Node not existing (file 'genicam_wrap.cpp', line 16130)".

**Comment by thiesmoeller** [comment]
:-)
To your issue :
Can you show the part of your code that triggers this error? Or a heavily reduced sample?

**Comment by s-kesh** [comment]
```
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice(info))
camera.Open()
camera.StaticChunkNodeMapPoolSize = camera.MaxNumBuffer.GetValue()
camera.ChunkModeActive = True
```

Everything works till setting ChunkNodeMapPoolSize, but the last line throws the error.

Again thanks for helping me.

**Comment by thiesmoeller** [comment]
As the current firmware of an acA1920-155um supports chunk mode....
a) one simple question: do you have more than one camera available and open the wrong camera and thus get the error?
     can you see the ChunkModeActive feature in the pylonviewer on your camera?
b) can you post the output of this?
```python
import pypylon.pylon as py
tlf = py.TlFactory.GetInstance()
cam = py.InstantCamera(tlf.CreateFirstDevice())
cam.Open()

print(cam.DeviceModelName())
print(cam.DeviceVersion())
print(cam.DeviceFirmwareVersion())

cam.Close()
```

**Comment by s-kesh** [comment]
a) No, I only have one camera.  But, yes I can not see ChunkModeActive feature in the pylon viewer. Maybe my firmware is out of date.
Here is the output
```
acA1920-155um
106879-03
106879-03;U;acA1920_155u;V0.4-3;0
```

Again Thanks for helping me.

**Comment by SMA2016a** [comment]
this camera is a prototype one, the firmware can not be updated in the field.
