### ISSUE TITLE
how to use FrameBurstStart with background loop on hardware trigger?

### ISSUE THREAD

**Issue by ridvanozdemir** [basler/pypylon#541]
is it possible to use basler aca2500-60uc camera in this combination?  
can you give me a quick code sample for this program?

**Comment by SMA2016a** [comment]
Please refer to this sample code. You need to register image handler

https://github.com/basler/pypylon/blob/master/samples/grabstrategies.py

**Comment by ridvanozdemir** [comment]
thank you
