### ISSUE TITLE
Sample build issue with blaze-101

### ISSUE THREAD

**Issue by maximehyh** [basler/pypylon#543]
Hello,

I am currently trying to build an application which will need to get access to a Blaze-101 from within a Ubuntu (20.04) based docker container. 

On a plain Ubuntu (20.04) OS (not in a container) I have managed to: 
1. Launch the pre build sample available at `./opt/pylon/bin/blazeLister`, which gives me the following output: 
```
S/N             IP Address              FW Version
XXXXXXX        10.100.104.127          fw-3.0.2-XXXXX;fw-3.0.2-0-XXXXX
Press ENTER key to exit.
```

2. Built and launch sample available at `./opt/pylon/share/pylon/Samples/blaze/cpp/build/FirstSample/FirstSample` which gives me: 
```
Connected to camera Basler blaze-101 (XXXXXXX)
User-defined name: 
Serial Number: 23780585
x=  21.0 y=  54.3 z=5171.6
 intensity=14426 confidence=  745
x=  21.1 y=  54.5 z=5192.8
 intensity=14341 confidence=  734
x=  21.1 y=  54.6 z=5198.9
 intensity=13706 confidence=  655
x=  21.1 y=  54.6 z=5194.3
 intensity=14530 confidence=  758
x=  21.1 y=  54.6 z=5194.0
 intensity=14791 confidence=  793
x=  21.1 y=  54.6 z=5194.2
 intensity=14262 confidence=  724
x=  21.1 y=  54.6 z=5198.6
 intensity=14678 confidence=  778
x=  21.1 y=  54.7 z=5204.1
 intensity=14384 confidence=  739
x=  21.1 y=  54.7 z=5202.6
 intensity=14203 confidence=  716
x=  21.1 y=  54.7 z=5204.5
 intensity=14035 confidence=  695

Press Enter to exit.
```

When doing the same thing **inside a docker container** I can launch the pre build sample and connect to the blaze with no issue, but when I successfully build and launch the other sample I get the following output: 
```
Exception occurred: 
The transport layer for device class 'BaslerGTC/Basler/GenTL_Producer_for_Basler_blaze_101_cameras' could not be created.

Press Enter to exit.
```

FYI I am using `--network host` when launching `docker run` in order to make sure that my container is bridged on the host network. That plus the fact that I can connect to the blaze camera with the pre build sample inside the container I believe we can opt out any network issue. Except if `./opt/pylon/bin/blazeLister` and `./opt/pylon/share/pylon/Samples/blaze/cpp/build/FirstSample/FirstSample` are connecting to the cameras in different ways (?).

 I am wondering if there could be a build issue when building inside the docker container (GCC version is 9.4.0 on pure Ubuntu 20.04 and inside Docker Ubuntu 20.04)? Or if maybe some specific packages missing could cause the build to succeed but not being able to connect to a camera? 

Thanks a lot

**Comment by thiesmoeller** [comment]
@maximehyh this is the issue tracker for the python binding to the pylon SDK. For request regarding the Blaze C++ SDK please contact your local support: https://www.baslerweb.com/en/sales-support/support-contact/

As one overall hint to your setup:
the blaze relies on GenTL technology for the driver implementation. If you haven't properly set the environment variable in to find this driver inside your container, the camera can't be detected.
The GENICAM_GENTL64_PATH environment variable not or not correctly set inside the docker container. Reason might be that no login shell is used in the container. Check the value of that env var outside of the container and set it in the container accordingly.

If you installed in default locations this should be the right value:
```bash
export GENICAM_GENTL64_PATH=/opt/pylon/lib/gentlproducer/gtl
```
