### ISSUE TITLE
Error when installing  Camera Enablement Package for NVIDIA®’s Jetson boards 

### ISSUE THREAD

**Issue by visionad** [basler/pypylon#555]
When i try to install this package on my jetson nano i have the following error:
![image](https://user-images.githubusercontent.com/118456889/202473724-65c195a2-e3fb-4353-abf2-650f1f8b5111.png)

On that list of hardware modules it should appear: 
 1. Adafruit SPH0645LM4H
  2. Basler camera overlay
  3. FE-PI Audio Z V2
But as you can see, the basler camera overley is missing. 

I have tried both the installation both with the setup.py automatic installation and the manual installation. The error appears in both, when it checks that the overly is available. 

The manual installtion guide says: 
_2. Ensure that the overlay is available by running:

    ```sh
    $ sudo /opt/nvidia/jetson-io/config-by-hardware.py -l
    Configurations for the following hardware modules are available:
    
    1. Adafruit SPH0645LM4H
    2. Basler camera overlay
    3. FE-PI Audio Z V2
    ```_

Im using a Jetson Nano with Jetpack 4.6.1-b110

I have also already installed pylon and pypylon, although i dont believe the issue is related to this

I cant find any similar error on the internet, 

Thank you in advanced

**Comment by SMA2016a** [comment]
do you need to have the latest CEP Version.   Contact your local distributor

**Comment by visionad** [comment]
Thank you for responding,

As far as i know, there is only one CEP Version for Jetson, so i dont have the possibility to upgrade the CEP,

Is there anything else i could do?

**Comment by visionad** [comment]
Solved,

In the tegra... .dts file, between the overley name and compatible lines it needs to be this line:
jetson-header-name = "Jetson 40pin Header"

Like this:

![image](https://user-images.githubusercontent.com/118456889/202712839-272fbb59-fce0-4166-9083-45a409474ef9.png)
