### ISSUE TITLE
where I can add the pylon-config file in windows 11

### ISSUE THREAD

**Issue by sulaimansiddiqi233** [basler/pypylon#561]
hello 
@SMA2016a @m-binev @thiesmoeller
we just want to run a make file in windows 11 but the get the errors as you can see in attachment file. after that Basler team send as a pylon-config file and they told to put it in the path (/opt/pylon/bin) but unfortunately in window 11 we could not find the path . so could help us in the issue. 
![image](https://user-images.githubusercontent.com/41513015/204086958-e257db86-bcd0-48dc-b2bd-b2de40e2eb44.png)

thank you.

**Comment by SMA2016a** [comment]
pylon sdk can not easy builld with mingw.  You need to tweak the header files.  pylon-config is just for Linux user only.

**Comment by sulaimansiddiqi233** [comment]
@SMA2016a so how can I run the makefile in windows.

**Comment by sulaimansiddiqi233** [comment]
we solve it
