### ISSUE TITLE
Windows下仅支持Python3.5以下版本吗？

### ISSUE THREAD

**Issue by Sakurachu** [basler/pypylon#574]
请问在Windows系统下仅支持Python3.4、3.5版本吗？不支持更高的版本了吗？

**Comment by SMA2016a** [comment]
您的问题已经在第一页得到解答。

请仅用英文发布您的问题

https://github.com/basler/pypylon

**Comment by Sakurachu** [comment]
Ok sorry, I saw on the first page that only 3.4,3.5, But I saw in https://github.com/basler/pypylon/releases pypylon 1.7.1 
# Fixed in the runtime error in binary Windows releases with python 3.5-3.8

**Comment by Sakurachu** [comment]
sorry, it's 1.7.2

**Comment by thiesmoeller** [comment]
@Sakurachu have you found the pypylon version you are searching for?

**Comment by Sakurachu** [comment]
> @Sakurachu您找到要搜索的 pypylon 版本了吗？
Python3.7 can be used

**Comment by Sakurachu** [comment]
> @Sakurachu您找到要搜索的 pypylon 版本了吗？

Yes。
