### ISSUE TITLE
Do you plan any support for ARM?

### ISSUE THREAD

**Issue by mouzkolit** [basler/pypylon#579]
Currently there is no way to install the software on an M1/M2

**Comment by thiesmoeller** [comment]
Apple silicon Support is planned. No release date yet.

Interim solution is to run in Rosetta emulated environment

**Comment by brandonrwin** [comment]
At this time, the Mac Pro is the only remaining Intel computer that can be bought, from Apple. Choosing to use a Basler camera in your projects means you'll lose ~30% performance in your app, from Rosetta emulation.

**Comment by thiesmoeller** [comment]
We have a first version running.
 Expect a first public release of pypylon for Apple Silicon  in the next weeks.

**Comment by thiesmoeller** [comment]
Release 2.2.0 with full support of macOS x86_64 and arm64 ( >= macOS 11 ) is out.

Available via pip install or releases page.
