### ISSUE TITLE
Can we use Basler cam on WSL platform?

### ISSUE THREAD

**Issue by nicolexi** [basler/pypylon#581]
![image](https://user-images.githubusercontent.com/31596975/215210604-8d0575fa-c7a7-4638-bca2-b93868114356.png)
Hi I tried tp attached the Basler camera to the WSL platform but it failed and saying: 
usbip: error: Attach Request for 1-23 failed - Device in error state

usbipd: error: Failed to attach device with busid '1-23'.

**Comment by thiesmoeller** [comment]
Never tried to get this running ... 
But as WSL is using USP/IP to transfer the data into the Linux domain ... This is might not be efficient enough to operate a high performance machine vision camera

**Comment by thiesmoeller** [comment]
From your list of devices ... There is no Basler camera visible.

**Comment by SMA2016a** [comment]
yes, I have tested only a GigE camera and it is working.

**Comment by SMA2016a** [comment]
did you install pylon SDK on your Windows machine?  

![grafik](https://user-images.githubusercontent.com/18481846/217934888-317fbf67-d227-49d7-8666-a4739303cffe.png)

**Comment by SMA2016a** [comment]
I can confirm that USB camera is working in WSL2

**Comment by jwongpic** [comment]
`PS C:\Windows\system32> usbipd wsl list
BUSID  VID:PID    DEVICE                                                        STATE
2-4    1050:0407  USB Input Device, Microsoft Usbccid Smartcard Reader (WUDF)   Not attached
2-11   0c45:6720  Integrated Webcam                                             Not attached
2-14   8087:0026  Intel(R) Wireless Bluetooth(R)                                Not attached
2-20   2676:ba02  Basler ace USB3 Vision Camera                                 Not attached

PS C:\Windows\system32> usbipd wsl attach --busid 2-20
usbipd: warning: Unknown USB filter 'CsDeviceControl' may be incompatible with this software; 'bind --force' may be required.
usbipd: warning: Unknown USB filter 'fuhub' may be incompatible with this software; 'bind --force' may be required.
usbip: error: recv op_common
usbip: error: query
usbipd: error: Failed to attach device with busid '2-20'.
`

I run into the same problem, I have the SDK installed. @SMA2016a , what are the commands you use to attach the camera to WSL?

**Comment by SMA2016a** [comment]
yes, you need usb driver  also in WSL
