### ISSUE TITLE
Noise Causes Trigger Problems for acA2500-60uc Camera

### ISSUE THREAD

**Issue by ridvanozdemir** [basler/pypylon#586]
I am using acA2500-60uc - Basler ace model camera and  a sensor's output signal as a trigger. After a trigger recieved I don't need new one in next 1000 ms. but sometimes cause of electronic noises camera get trigger several times in seconds. I use "LineDebouncer" function but it's not enough.
How can I fix this problem? Can I add a wait command after grabbing ?

**Comment by PolymaTh-EE98** [comment]
Try also falling edge on the trigger. Noise usually needs to be prevented though. Separate your cables for example.

**Comment by thiesmoeller** [comment]
In addition to proper electrical setup, you can set the AcquisitionRate feature. This will set the minimum time between accepted trigger signals

**Comment by ridvanozdemir** [comment]
thank you!
