### ISSUE TITLE
Multiple cameras Camera Id to Picture.

### ISSUE THREAD

**Issue by aidonchuk** [basler/pypylon#59]
Hi! How to get camera id of the picture while multiple cameras grabbing? Thx.

**Comment by thiesmoeller** [comment]
Every Grabresult contains a reference to the camera the image came from:

see [here](https://github.com/basler/pypylon/blob/6cf4f6dd270772dba1a60996546e5e5199da7b8d/samples/grabmultiplecameras.py#L82)
