### ISSUE TITLE
trigger mode on emulation

### ISSUE THREAD

**Issue by kafiamine** [basler/pypylon#600]
i try to use hardware trigger in emulation mode, but i got an error:
here the code that i wrote:

instance.TriggerMode.SetValue("off")
instance.TriggerSelector.SetValue("FrameStart")
instance.TriggerSource.SetValue("Line1")
instance.TriggerActivation.SetValue("RisingEdge")
instance.TriggerMode.SetValue("On)

and here the error that i got:
instance.TriggerSelector.SetValue("FrameStart")
  File "/usr/local/lib/python3.9/site-packages/pypylon/genicam.py", line 2316, in SetValue
    return _genicam.IEnumeration_SetValue(self, entry)
_genicam.InvalidArgumentException: Feature 'TriggerSelector' : cannot convert value 'FrameStart', the value is invalid. : InvalidArgumentException thrown in node 'TriggerSelector' while calling 'TriggerSelector.FromString()' (file 'Enumeration.cpp', line 134)

note that this code works fine in real camera, any idea about the pb, please?

**Comment by SMA2016a** [comment]
I think that the EMU camera does not have trigger settings.
