### ISSUE TITLE
weird image from pylon

### ISSUE THREAD

**Issue by pourfard** [basler/pypylon#606]
Hi,

We have a USB camera model acA2440-35uc, but when grab image from camera there is a weird output like zebra
![1](https://user-images.githubusercontent.com/46415911/235352272-4e7ee62d-0849-4bb1-b59b-f1babc6a196e.jpg)

Sometimes there is no problem and the output image is ok.

Any idea or solution?

**Comment by thiesmoeller** [comment]
This is one of the  camera testimages.
Maybe you have this configured in the user set stored in flash.

https://docs.baslerweb.com/test-images.html

**Comment by pourfard** [comment]
> This is one of the camera testimages. Maybe you have this configured in the user set stored in flash.
> 
> https://docs.baslerweb.com/test-images.html

Thanks for your quick response. But test image selector is disabled.
![Screenshot from 2023-04-30 16-09-49](https://user-images.githubusercontent.com/46415911/235353500-2497c0e4-d6bd-441f-bb2a-56be2787ef9e.png)

**Comment by SMA2016a** [comment]
the camera get to hot. Cool down the camera. Please check in the camera node device control for the current temperature of FPGA or Sensor

**Comment by pourfard** [comment]
Thanks @SMA2016a, It seems that temperature is high in that camera.
