### ISSUE TITLE
using selector fields in setting camera parameters

### ISSUE THREAD

**Issue by MLankheet** [basler/pypylon#614]
Hi, 
I am trying to control basler usb3 cameras from python with pypylon. I start from a .psf file from the pylonviewer, and then modify the fields I like to adjust. That  works fine, but I do not understand how to use the 'Selectors'. Some settings are a combination of e.g., a LineSelector and then the actual setting, e.g. LineMode. I understand that these settings can have different values based on the selector, but it is unclear to me how I can use the selector programmatically in setting the values.
I went through all examples but did not find it anywhere. 

best regards, 
Martin L

**Comment by thiesmoeller** [comment]
Hi Martin,

it works exactly as in the c++ code.

If you want to set e.g. the LineInverter of Line1 you have to:

```python
cam.LineSelector.SetValue("Line1")
cam.LineInverter.SetValue(true)
```

first the selector then the selected feature.

**Comment by MLankheet** [comment]
Thanks a lot, 
That actually makes sense. 
M

**Comment by MLankheet** [comment]
Hi,
Just for my understanding:
In the psf file from the pylonviewer multiple identical settings of a selector field have no effect?
This is part of the file:
TriggerSelector     FrameBurstStart
TriggerMode  Off
TriggerSelector     FrameStart
TriggerMode  Off
TriggerSelector     FrameStart
TriggerSelector     FrameBurstStart

The fifth line setting triggerselector to framestart is obsolete? Or does this have a purpose?

Thanks a lot for your help,
Martin

**Comment by thiesmoeller** [comment]
You can really thing of the selector as a multiplexer that you have to set to route the feature accesss to the right feature.

See below drawing as an explanation:

![image](https://github.com/basler/pypylon/assets/5516325/589e707e-fb6f-46b3-bb62-5d04dbd28b29)

So setting the Selector multiple times to the same value has no effect, as it just sets the routing of the subsequent feature access to the same value.

Reason for the selectors was to minimize the API surface. As there are camera feature blocks with e.g. 10 features each that exist in 10 different ways.... this would end up in 100 different feature names, without selectors.
