### ISSUE TITLE
No device is available

### ISSUE THREAD

**Issue by pourfard** [basler/pypylon#621]
Hi, I have a problem with new  5mp USB device. I have tested three different USB 3.0 cables.

1- Sometimes I can grab image with abnormal FPS (5-10 FPS).
2- After a few seconds throws an exception and the camera disappears in lsusb output.
**3- Most of the time lsusb command shows the camera but it cannot find device.**
4- It cannot find even another GigE camera in the same network. The GigE camera IP address is pinging.

Platform (SBC): Linux orangepi5 5.10.110-rockchip-rk3588 #1.1.0 SMP aarch64 aarch64 aarch64 GNU/Linux
Python: 3.10
pypylon: 2.2
Pylon: 7.3.0

Can it be related to power supply of the SBC? or related to power supply of the camera?

![Screenshot from 2023-06-15 11-49-01](https://github.com/basler/pypylon/assets/46415911/f6a2f26e-f964-42fc-9a04-13fc570214af)

**Comment by SMA2016a** [comment]
will you try your script as sudo please

**Comment by pourfard** [comment]
I'm so sorry, I tested a lot of ways, but finally I tested with another cable (forth cable) and there is no problem. The problem were the broken cables.

**Comment by devimauz** [comment]
sudo helped me. Thanks :)
