### ISSUE TITLE
How do I ensure the captured image is newest ?

### ISSUE THREAD

**Issue by larry50708** [basler/pypylon#623]
This is my project to capture the PCBA and Chip materials (die-bonding process).
As following, the configuration is that:
1. Basler Area-scan camera [Basler ace 2 a2A5328-15umPRO]
2. USB3.0 interface.
3. pypylon SDK.

Now, I have two questions:

1. **How do I ensure the captured image is newest ?**
    
    First, I commanded the continuous shot when initializing the CCD.

   `self.camera.StartGrabbing(pylon.GrabStrategy_LatestImageOnly)`

    When I wanna to get the images, I commanded this code:

    ```python
    def GetImage(self, isWaited = True):
        #   Get the instant images
        if self.ThreadLock.locked() and not isWaited and self.cv_img is not None:
            return self.cv_img
        else:
            with self.ThreadLock:
                retry = 0
                while self.camera.IsGrabbing():
                    grab_result = self.camera.RetrieveResult(1000, pylon.TimeoutHandling_Return)
                    if grab_result.IsValid():
                        if grab_result.GrabSucceeded():
                            #   Access the image data
                            image = self.converter.Convert(grab_result)
                            img_buff = image.GetArray()
                            if self.rotate is not None:
                                self.cv_img = cv2.rotate(img_buff, self.rotate)
                            else:
                                self.cv_img = img_buff
                            return self.cv_img
                        else:
                            grab_result.Release()
                    else:
                        retry+=1
                        if retry > self.FailRetry:
                            break
    ```

    `RetrieveResult()` can grab the latest image from the address of output buffer, and then clear that address to wait receiving        the next image. **How do I ensure the newest images in the output buffer are real-time? How to update the images in the output buffer?**

2. There are different material types of both the PCBA and Chip, in that case, I should change different exposure times to attain 
    appropriate images. As following, the code is:

    ```python
    def SettingExposure(self, exp_time) -> bool:
        #   Basler setting unit is us
        if self.camera.IsOpen():
            self.camera.ExposureTime.SetValue(exp_time * 1000)
            return True
        else:
            return False
    ```

    However, I captured images with the wrong exposure time. I ensure that I command the setting of exposure time. **Which problems occured that I didn't attain the real-time images from the output buffer, or  the setting of exposure time was delayed?**

    I may study the tutorials of the Basler pylonviewer SDK. `Sequencer` is a method can change the camera parameters rapidly. In pypylon, do it have the same methods to solve this problem?

    `Sequencer`: [https://docs.baslerweb.com/sequencer-(ace-classic-u-l-usb)](https://docs.baslerweb.com/sequencer-(ace-classic-u-l-usb))

    Welcome to discuss !! Thanks for everyone !!

**Comment by thiesmoeller** [comment]
With the grab strategy "LatestImageOnly", you have already activated the mode, where pylon's capture engine takes care of always delivering the latest image.

Your code might partially circumvent this? Or do you expect to be able to call `get_image` multiple times between receiving real frames.

One note regarding LatestimageOnly: this is the latest image fully available in your host. The acquisition is in the past, regarding the time of your get_image call.

Regarding sequencer. Yes. This is the fasted way to switch between multiple camera settings on frame-by-frame base.

As you have an ace2 model, the manual relevant for you is: https://docs.baslerweb.com/sequencer-(ace-2-and-boost-r).

Every feature needed to program the sequencer is supported in pypylon.

To assist here, more details about the timing relationships of capturing images and modifying the operating point depending on components to check would be required.
