### ISSUE TITLE
High temperature

### ISSUE THREAD

**Issue by pourfard** [basler/pypylon#628]
Hi,

I have an ace2 5 mega pixels USB-3 camera and I want to use it outdoor. I have used a CCTV housing with sun shield and currently weather temperature is about 43 degrees in our city. The camera's temperature is about 80 degrees and it cannot capture image (and just shows template image). I have used two small 5V fans and heat sinks to reduce the temperature and I only grab 10 frames per second. Is there any solution or idea to grab frames in this condition?

Thanks

**Comment by SMA2016a** [comment]
I think only active cooling will help you since the environment temperature is quite high.

**Comment by pourfard** [comment]
We had some LEDs in front of the camera's housing and we turned all them off and now the camera's temperature is about 68 degrees.
