### ISSUE TITLE
How to specifically call to cameras from two different script

### ISSUE THREAD

**Issue by tomriddle54** [basler/pypylon#63]
I want to run first camera from first group second camera from another script for example this is a code to run first camera
# conecting to the first available camera
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())
How to do this with second camera from another script

**Comment by thiesmoeller** [comment]
you can always filter the devices on opening.

e.g. on Serial Number
```
import pypylon.pylon as py
info = py.DeviceInfo()
info.SetSerialNumber("1234567")
cam  = py.InstantCamera(py.TlFactory.GetInstance().CreateFirstDevice(info))
```
