### ISSUE TITLE
Does pypylon support BoostV?

### ISSUE THREAD

**Issue by ensotseng** [basler/pypylon#633]
As title, I am wondering does pypylon support BoostV?

**Comment by thiesmoeller** [comment]
Hi @ensotseng, 

in principle: *yes*. pypylon supports any camera that is supported by pylon.

At the moment pypylon is released with slightly older pylon versions on pypi, so it might be that the pylon SDK version is not fresh enough for boost-v. -> You can always build on your own with a newer pylon release.... but `pip install pypylon` is definitly more convenient.

On which operating system do you want to work with Boost-V?

**Comment by SMA2016a** [comment]
Since the current pypylon supports, I close this request
