### ISSUE TITLE
Asynchronous processing of grabbed images

### ISSUE THREAD

**Issue by danielkonecny** [basler/pypylon#636]
Hi! I am trying to boost the performance of image capturing with pypylon from my Basler camera. I am currently working with software trigger and processing images in OnImageGrabbed method from class that inherits pylon.ImageEventHandler. Bad I can't get the images to save quickly enough before the next image comes in.

I tried saving images in BMP format to reduce the computational power needed and got some performance boost, but not enough. I am saving the images to an SSD, so the writing speed should not be an issue. From my measurements, converting grab result (with a pylon.ImageFormatConverter) takes a significant amount of time and then writing image file to my SSD takes some as well.

My idea was to delegate the image processing and saving to a separate "thread" that can run while next image is captured and not block the camera by staying in the OnImageGrabbed method. The images are shared in a queue among the main and image processing thread. But doing so didn't speed up the saving and recording at all.

From reading multiple issues in this repo, I have come to conclusion that this will not work since the Image Event Handler is in its own separate thread by default and does not block the software trigger. But I did not find any statement that supports this directly, only indirectly. I tried finding the original pylon code in C++ to check this in the official implementation but was not successful either. **Can someone please confirm or reject my hypothesis that the image event handling has its own separate thread?**

And if it's not in a separate thread (and therefore can be optimized in some way), is there any reference implementation with the Python _threading_ module that I could inspire from?

I was also thinking about using Python's _asyncio_ to delegate the computational resources even more efficiently but was not able to implement it into the image event handling since the image handling callback feels like a blackbox to me and I can't figure out a way how to incorporate coroutines into it.

Thanks in advance!

**Comment by SMA2016a** [comment]
[Can someone please confirm or reject my hypothesis that the image event handling has its own separate thread?] Yes. 

how long takes the image conversion and what is the image size?  What is the target fps?

**Comment by danielkonecny** [comment]
Thanks with the info about image event handling being in a separate thread. Then, I suppose, there is no way to speed things up with Python's threading module, it can only decrease the performance because of the thread handling overhead. The same probably goes for any solution with the asyncio module.

I'm using the conversion to BGR8 packed and it takes mostly around 10 ms but sometimes goes up to 20 ms (measured with time.perf_counter).

My targeted fps is 60 with 1920×1080 resolution (ideally max resolution of the 5MPx camera (a2A448-75ucPRO) but Full HD would be sufficient). Currently I can get 1920×1080 resolution with 25 fps with no significant framerate drop but that is as high as I can get.

**Comment by danielkonecny** [comment]
I solved all my performance issues with a multiprocessing producer-consumer architecture of my application. I think that others might find this solution helpful, so I'll briefly describe it before closing the issue.

I am using a main process to control and trigger (SW) all cameras (producer process) and then I have subprocess for each camera that does image conversion, resizing, and saving to SSD (consumer processes). Images are shared via multiprocessing's Shared Memory in a numpy nd-array. I am using two shared memory objects for each camera, so that one can be used by the camera to store new images and the other has its images converted, resized, and saved in the consumer process. After one of those shared memory objects is full with the new images, shared memory objects are swapped, so there is no delay in recording. Therefore, one strong assumption has to be fulfilled - images have to be converted (debayering), resized (if lower resolution needed), and saved to SSD faster than how fast are new images produced. Otherwise, some recorded frames will get lost and replaced by some that are from a different timestamp. Lastly, I am using multiprocessing Event objects to communicate between processes.

This solution is way faster than just using pypylon normally. Any threading/asyncio solution will not improve performance of pure pypylon. Previously, I was only able to run FullHD@25, now I can run FullHD@75 easily. Also, recording with multiple cameras was also previously not an option but now I am almost able to run FullHD@60 with one color and one mono camera. With a laptop with better performance, I can run these two cameras at 60 fps easily, more could be added.

I can't share my code but I believe this description should be sufficient. Hope it helps!

**Comment by thiesmoeller** [comment]
Thanks @danielkonecny for providing the feedback to your high performance solution!
With upcoming removal of the python GIL .. there will be more solutions just based on threads.

**Comment by spoorgholi74** [comment]
@danielkonecny Thanks for the description of the solution. Is it possible to link to the code that you have worked on?

**Comment by danielkonecny** [comment]
@spoorgholi74 I cannot provide the code unfortunately. But if you have any specific question, I am happy to help.
