### ISSUE TITLE
AccessException: Node os not writable

### ISSUE THREAD

**Issue by Valentine323** [basler/pypylon#639]
Hi, I'm aiming to use the Basler Ace 2 camera's 6pin output to send a trigger signal to the IR light connected to it, but upon configuring the `LineMode` and or `LineSource` atributes 
```
line_selector_entries = camera.LineSelector.GetEntries()
camera.LineSelector.SetValue(line_selector_entries[0].GetSymbolic())
camera.LineMode = 'Output'
line_source_entries = camera.LineSource.GetEntries()
camera.LineSource.SetValue(line_source_entries[5].GetSymbolic())
```
I get the following error:
` File "C:\gitlab\capture\venv\lib\site-packages\pypylon\genicam.py", line 2052, in SetValue
    return _genicam.IEnumeration_SetValue(self, entry)
_genicam.AccessException: Node is not writable : AccessException thrown in node 'LineSource' while calling 'LineSource.FromString()' (file 'valuet.h', line 85)
`
The `camera` object is a `pylon.InstantCameraArray` instance.
[This](https://github.com/basler/pypylon/issues/112) post suggests to first open the camera object, but it does not help.
In one scenario I managed to set the `camera.LineMode` attribute, but after stopping the script and restarting it, it does no longer work. I've also disconnected/reconnected the camera.

**Comment by SMA2016a** [comment]
did you open the camera before accessing the camera's parameter?

camera.Open()

**Comment by Valentine323** [comment]
Yes, I did.

**Comment by SMA2016a** [comment]
the print line_selector_entries[0].GetSymbolic() and  line_source_entries[5].GetSymbolic() and post the out put,please

**Comment by Valentine323** [comment]
`line_selector_entries[0].GetSymbolic()` is `'Line1'`
`line_source_entries[5].GetSymbolic()` is `'ExposureActive'`

**Comment by SMA2016a** [comment]
please check  with pylonviewer if Line1 can be set as output. I think this is not the case.   It may be this can be used as input only.

camera.LineSelector.SetValue("Line2")
camera.LineMode.SetValue("Output")
camera.LineSource.SetValue("AcquisitionActive")

try this out

**Comment by Valentine323** [comment]
Ok, I opened it in pylon Viewer and discovered that indeed, Line 1 cannot be set as an output. It works now with Line2. Thank you!
