### ISSUE TITLE
Error in Grab.py example

### ISSUE THREAD

**Issue by LucasC19** [basler/pypylon#673]
Hello,

I have tried to run the Grab example using both python and C++ and I had he same problem to find the camera with the command:

`camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())`

This problem was solved by substituting this line of code by:

`tlf = pylon.TlFactory.GetInstance()`
`tl = tlf.CreateTl('BaslerGigE')`
`cam_info = tl.CreateDeviceInfo()`
`cam_info.SetIpAddress('192.168.131.90')`
`camera = pylon.InstantCamera(tlf.CreateDevice(cam_info))`

But now I am getting the following error with the image transferring:

Using device  a2A5328-4gcBAS
An exception occurred.
Grab timed out. Possible reasons are: The image transport from the camera device is not working properly, e.g., all GigE network packets for streaming are dropped; The camera uses explicit triggering (see TriggerSelector for more information) and has not been triggered; Single frame acquisition mode is used and one frame has already been acquired; The acquisition has not been started or has been stopped. : TimeoutException thrown (file 'InstantCameraImpl.h', line 1034)

Can someone please help me figure out how to fix this problem?

Thanks in advance

**Comment by SMA2016a** [comment]
what was the problem with camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())?

would you post the IP of the camera and the network interface?


try this code:

ip_address = "192.168.131.90"
cam_info = pylon.DeviceInfo()
cam_info.SetPropertyValue('IpAddress', ip_address)
cam = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice(cam_info))
print("Using device ", cam.GetDeviceInfo().GetModelName())

cam.Open()
res = cam.GrabOne(1000)

**Comment by LucasC19** [comment]
Hi, thanks for the response,

When I try to connect the camera with "camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())" I get the following error:

![Screenshot from 2023-10-30 07-20-41](https://github.com/basler/pypylon/assets/102183869/d26f8c5a-368f-491b-b105-e4f91462ad1d)

I have tryed the code you suggested as well and I also got an error:

![Screenshot from 2023-10-30 07-24-00](https://github.com/basler/pypylon/assets/102183869/3ede6df3-561e-47bf-8970-0db5f34b0756)

I was able to ping the camera (With the IP provided in the code) on terminal and the code I used in the first post was still able to connect with the camera.

**Comment by thiesmoeller** [comment]
What is your OS, and your platform.

Have you run the full pylon sdk installation including pylon viewer? https://www2.baslerweb.com/en/downloads/software-downloads/#version=7.4.0;type=pylonsoftware;language=all
There we also have a ipconfigurator tool, that allows to debug connection issues.

**Comment by LucasC19** [comment]
I am trying to run the code in a Dell Vostro with Ubuntu 22.04. I have installed the "Basler pylon Camera Software Suite", but not the "CodeMeter" or the "CoaXPress Cameras", do I need those?

I don't think is a connection or IP issue, since I am able to connect and configure the camera using the user interface

**Comment by thiesmoeller** [comment]
It seems, that the camera is not connected in a standard way to your computer.

Can you paste a screenshot of the ipconfigurator?
You write that can "connect and configure the camera using the user interface", but can you also capture video?

**Comment by LucasC19** [comment]
I have looked at IP Configurator and indeed the  Subnet Mask was different from the computer. I have corrected that and now it is working. 
Thank you very much for the help.
