### ISSUE TITLE
 pypylon for windows machine

### ISSUE THREAD

**Issue by Thyagutamizhan** [basler/pypylon#68]
how to install pypylon in windows 10 64 bit machine with python 3.6.3 installed in it?

error message:
Collecting python-pylon
  Could not find a version that satisfies the requirement python-pylon (from versions: )
No matching distribution found for python-pylon

**Comment by thiesmoeller** [comment]
It's pypylon

https://pypi.org/project/pypylon/

**Comment by thiesmoeller** [comment]
on a windows machine you could simply call:

`pip install pypylon`

to help in your case, please also post the cmdline you use otherwise it is tricky to help

**Comment by Thyagutamizhan** [comment]
pip install pypylon shows th error like this

Collecting python-pylon
Could not find a version that satisfies the requirement python-pylon (from versions: )
No matching distribution found for python-pylon

**Comment by thiesmoeller** [comment]
... this sounds as if you have a configuration error.

on your machine you described with: `windows 10 64 bit machine with python 3.6.3` with an up to date pip it must work.

To aid in debugging:
please call:

`pip.exe search pypylon -v`

This must print out:

```
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "POST /pypi HTTP/1.1" 200 307
pypylon (1.3.1)                - The python wrapper for the Basler pylon Camera Software Suite.
pypylon-opencv-viewer (1.0.3)  - Impro function application while saving and getting image
```

**Comment by Thyagutamizhan** [comment]
thanku thiesmoeller, 
i have installed pypylon with the reference of frankkarstens
