### ISSUE TITLE
Is the pylon.PylonInitialize form correct?

### ISSUE THREAD

**Issue by Wiktor010** [basler/pypylon#685]
import cv2
from pypylon import pylon
import numpy as np
from pypylon.genicam import GenericException

def capture_image_basler(frame):
    # Initialize Pylon
    pylon.PylonInitialize()

    try:
        # Create an instant camera object
        camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())

        # Open the camera
        camera.Open()

        # Set image parameters
        camera.LightSourcePreset = pylon.LightSourcePreset_Off
        camera.BalanceRatioSelector = pylon.BalanceRatioSelector_Red
        camera.BalanceRatio = 2.0
        camera.BalanceRatioSelector = pylon.BalanceRatioSelector_Blue
        camera.BalanceRatio = 2.0
        camera.ReverseX = True
        camera.ReverseY = True

        # Grab a single image
        img = camera.GrabOne(10000)

        # Create a pylon image format converter and pylon image
        converter = pylon.ImageFormatConverter()
        converter.OutputPixelFormat = pylon.PixelType_BGR8packed
        pylon_image = converter.Convert(img)

        # Create an OpenCV image from the pylon image
        buffer = pylon_image.GetBuffer()
        image_array = np.ndarray(shape=(img.GetHeight(), img.GetWidth(), 3), dtype=np.uint8, buffer=buffer)

        # Copy the image array to the provided frame
        np.copyto(frame, image_array)

        # Close the camera
        camera.Close()

    except pylon.GenericException as e:
        print(f"Exception: {e.GetDescription()}")

    # Terminate Pylon
    pylon.pylonTerminate()

    return frame

frame = np.zeros((500, 500, 3), dtype=np.uint8)
capture_image_basler(frame)

/usr/bin/python /home/pi/Wiktor/classification.py
Traceback (most recent call last):
  File "/home/pi/Wiktor/classification.py", line 53, in <module>
    capture_image_basler(frame)
  File "/home/pi/Wiktor/classification.py", line 8, in capture_image_basler
    pylon.PylonInitialize()
AttributeError: module 'pypylon.pylon' has no attribute 'PylonInitialize'

**Comment by bjoernrennfanz** [comment]
Hi,

you don't have to call PylonInitialize or pylonTerminate, this is already done by the python wrapper layer.

With best regards
