### ISSUE TITLE
Settting Camera Exposure, and Loading pfs file.

### ISSUE THREAD

**Issue by GerrikLabra** [basler/pypylon#695]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

Hi all, 2023 version problems.

Able to setup up camera to record at high framerate using arduino to trigger captures, but the method to set a camera's property of exposure is missing as well. Previous threads (link1)[https://github.com/basler/pypylon/issues/291] and (link2)[https://github.com/basler/pypylon/issues/181] show exposure being codeable, but it doesn't show up in my pypylon library.

In pylon viewer(image attached), you can see I set the exposure relatively well, but when I open the AVI generated from my python the exposure is terrible.

from pypylon import pylon, genicam
from imageio import get_writer
import sys, time, datetime, numpy
with get_writer(
    path+file_name+".avi",  # save as avi
    format="FFMPEG",
    mode="?"
) as writer:
    print("Opening camera")
    camera.Open()
    ############# Problem Area  ############################
    camera.ExposureTime.SetValue(2000)
   ###################################################

    camera.StartGrabbing()
    frame_tracker_pos=[]
 
The above returns the following
 File "Python Scripts\one_camera_V5.0_TTL_Pulse.py", line 72, in <module>
    camera.ExposureTime.SetValue(100)
 File "anaconda3\Lib\site-packages\pypylon\pylon.py", line 4350, in __getattr__   
    return self.GetNodeMap().GetNode(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "anaconda3\Lib\site-packages\pypylon\genicam.py", line 1118, in GetNode     
    return _genicam.INodeMap_GetNode(self, Name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_genicam.LogicalErrorException: Node not existing (file 'genicam_wrap.cpp', line 16504)

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup & camera model(s) used

64 bit windows 11, basler aca1300_60gcAMZ

### Runtime information:

```shell
pylon Viewer 7.4.0.14100
pylon release 7.4.0.14900
```

**Comment by HighImp** [comment]
Hi @GerrikLabra ,

The gige ace1 is using another Standard Feature Naming Convention (SFNC) Version. 

camera.ExposureTime.Value = 200
is called:
camera.ExposureTimeAbs.Value = 200
In your case.

You can configure every feature in the feature tree, to get the correct names, open the pylon viewer and have a look at the feature discription window.

**Comment by GerrikLabra** [comment]
Thanks for the pointer.  I looked at the Basler Viewer,  and found the attached documentation. Its frustrating, because apparently I have no access via those methods or yours. Pylon viewer is not open when I set these values. Don't think its the model, or the documentation might change.

File "c:\Users\Gerrik\Documents\Visual Studio 2022\python\one_camera_V5.2b_TTL_Pulse+multicam+multiprocess.py", line 27, in find_cams
    camera.ExposureTimeAbs.Value= 200
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerrik\anaconda3\Lib\site-packages\pypylon\genicam.py", line 1831, in SetValue
    return _genicam.IFloat_SetValue(self, Value, Verify)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_genicam.AccessException: Node is not writable. : AccessException thrown in node 'ExposureTimeAbs' while calling 'ExposureTimeAbs.SetValue()' (file 'floatt.h', line 85)


camera.ExposureTimeAbs.SetValue(200)
  File "C:\Users\Gerrik\anaconda3\Lib\site-packages\pypylon\genicam.py", line 1831, in SetValue
    return _genicam.IFloat_SetValue(self, Value, Verify)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_genicam.AccessException: Node is not writable. : AccessException thrown in node

**Comment by thiesmoeller** [comment]
For readability of all your code references, please surround them with triple back quotes. 

````
```python
  Your code 
```
````

On docs.baslerweb.com you have to select your camera in the top right.
 Then you can get even python samples now ( since last Friday ) 

Typical workflow to  explore the interface is by developing in jupyter lab or notebook. Then you'll get dynamic auto completion.

The companion repository https://github.com/basler/pypylon-samples gives you all the background

**Comment by GerrikLabra** [comment]
Your script works. Since this seems more of an issue of correctly using the basler docs website, I will learn how to hunt solutions there. Thank you both.
