### ISSUE TITLE
Unable to grab colour image

### ISSUE THREAD

**Issue by kenny-kong-facemo** [basler/pypylon#7]
img = grabResult.Array gives grab scale image only.

How can I the RGB format?

**Comment by basler-oss** [comment]
Hi Kenny, have a look at this [example at ImagingHub/GitHub](https://github.com/StudentCV/face_detection). It shows how to grab and display a color imgage.

**Comment by LucasVandroux** [comment]
@kenny-kong-facemo your problem might be similar to mine and the solution I used might help you. Have look at #3 for more information.

**Comment by stefanklug** [comment]
I guess this is solved.
