### ISSUE TITLE
Question about function PylonInitialize in multithreads

### ISSUE THREAD

**Issue by Felix00643298** [basler/pypylon#708]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

I am wondering if I have 2 basler cameras, can I call PylonInitialize twice in each individual basler camera object in 2 seperate threads?

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup & camera model(s) used

ubuntu 18.04
gige cam

### Runtime information:

```c++
basler::basler()
{
    PylonInitialize();
}
basler::~basler()
{
    PylonTerminate();
}
```

**Comment by thiesmoeller** [comment]
https://docs.baslerweb.com/pylonapi/cpp/namespace_pylon#function-pyloninitialize

Paragraph 4': it is recounted ..
So yes you can
