### ISSUE TITLE
basler USB3 camera field of view

### ISSUE THREAD

**Issue by Mamooshe** [basler/pypylon#724]
### Describe the issue:

I work with the Basler gray camera using python API. Unfortunately the fov is about 20 degress which very small. Why is it too small? Is there a way which tune it to maximum in python script? if yes How?
Thanks

### Error message:

```shell
FOV is small
```

### Is your camera operational in Basler pylon viewer on your platform

Basler daA1920-160um(s-mount) usb3.0 camera

### Hardware setup & camera model(s) used

nvidia jetson nano

### Runtime information:

```shell
terminal
```

**Comment by thiesmoeller** [comment]
Please fill in the camera model that you use. And your lens

**Comment by Mamooshe** [comment]
> Basler daA1920-160um(s-mount) usb3.0 camera

Basler daA1920-160um(s-mount) usb3.0 camera

**Comment by thiesmoeller** [comment]
And your lens

**Comment by Mamooshe** [comment]
> And your lens

Lens Evetar M12B1618WM12 F1.8 f16mm 1/2

**Comment by Mamooshe** [comment]
![Screenshot 2024-02-21 225610](https://github.com/basler/pypylon/assets/119535164/e2ea18b4-8953-49d0-ba58-6ec4eaff689b)
according to datasheet it's around 20 degress. Can you suggest a lens which doesn't limit the FOV?

**Comment by thiesmoeller** [comment]
https://www.baslerweb.com/en/tools/lens-selector/

**Comment by SMA2016a** [comment]
please remember that this is nothing related to pypylon. 

you can order one of the following items on Basler Website:
Product ID :  2200001058      80 degrees Horizontal
                   2200001060     40 degrees Horizontal 

Please feel free to close this issue, if you find the right solution.
