### ISSUE TITLE
Camera emulation with pypylon

### ISSUE THREAD

**Issue by rkantos** [basler/pypylon#73]
Is there sample code or what are the corresponding functions shown in the Basler docs for samples for achieving camera emulation with Python? 

see: https://docs.baslerweb.com/#t=en%2Fcamera_emulation.htm

**Comment by thiesmoeller** [comment]
As pypylon is using the pylon SDK it works the same.

Just set environment var PYLON_CAMEMU to the number of emulated devices you want

grep for the PYLON_CAMEMU in the testfolder, it used multiple times , for reference

**Comment by rkantos** [comment]
Thanks, it works as expected. Any idea how I could set a custom image that scan from from right/left much like the available default gradients?

**Comment by thiesmoeller** [comment]
the test patterns that the camera emulation generates are fixed, and not adjustable by the user.

**Comment by thiesmoeller** [comment]
@rkantos  ... just learned that the current pylon base supports loading your own images into the emulation:

```python
import numpy as np
import matplotlib.pyplot as plt
import pypylon.pylon as py
import cv2
import os
import tempfile
```

# Create custom image data for pylon cam_emu


```python
# Setup 1080p
width = 1920
height = 1080
```


```python
test_pattern = np.fromfunction(lambda i, j, k: j % 256, (height, width,3 ), dtype=np.int16)
```


```python
test_pattern[:,:,0]
```




    array([[  0,   1,   2, ..., 125, 126, 127],
           [  0,   1,   2, ..., 125, 126, 127],
           [  0,   1,   2, ..., 125, 126, 127],
           ...,
           [  0,   1,   2, ..., 125, 126, 127],
           [  0,   1,   2, ..., 125, 126, 127],
           [  0,   1,   2, ..., 125, 126, 127]], dtype=int16)




```python
img_dir = tempfile.mkdtemp()

for i in range(256):
    pattern = np.roll(test_pattern,i,axis=1)
    cv2.imwrite(os.path.join(img_dir,"pattern_%03d.png"%i), pattern)
```


```python
# enable emulation 
import os
os.environ["PYLON_CAMEMU"] = "1"
```


```python
cam = py.InstantCamera(py.TlFactory.GetInstance().CreateFirstDevice())
cam.Open()
```

setup image path to current 


```python
cam.ImageFilename = img_dir
```


```python
# enable image file test pattern
cam.ImageFileMode = "On"

# disable testpattern [ image file is "real-image"]
cam.TestImageSelector = "Off"

# choose one pixel format. camera emulation does conversion on the fly
cam.PixelFormat = "Mono8"
```


```python
cam.StartGrabbingMax(10)

while cam.IsGrabbing():
    res = cam.RetrieveResult(1000)
    print( res.Array[0,:])
    res.Release()
    
cam.StopGrabbing()
```

    [  0   1   2 ... 253 254 255]
    [127   0   1 ... 252 253 254]
    [126 127   0 ... 251 252 253]
    [125 126 127 ... 250 251 252]
    [124 125 126 ... 249 250 251]
    [123 124 125 ... 248 249 250]
    [122 123 124 ... 247 248 249]
    [121 122 123 ... 246 247 248]
    [120 121 122 ... 245 246 247]
    [119 120 121 ... 244 245 246]



```python
cam.Close()
```

**Comment by rkantos** [comment]
Thanks, that is perfect and solves the "problem" in the title. Since it doesn't seem to be possible to emulate video this way.. Is there an efficient way to load the images first to computer memory and then play them back as fast as possible (or whatever the cameras can do.. e.g. a few hundred fps) ?

**Comment by pault587** [comment]
I just save all the images in a folder and loop the files reading them one at a time. The images load very quickly. For me the bottleneck is processing them not loading them. CV2 imread or PIL something like that will load images...

**Comment by thiesmoeller** [comment]
@rkantos  if you lower the value of `ExposureTimeAbs`  you can increase the framerate.
As the simulated camera has no real Readout-time ... the ExposureTime ... is the Frameperiod...

**Comment by rkantos** [comment]
> I just save all the images in a folder and loop the files reading them one at a time. The images load very quickly. For me the bottleneck is processing them not loading them. CV2 imread or PIL something like that will load images...

Hmm.. Perhaps you are right.. Currently with ~2600 images with size of 1000x100, I can only reach ~70fps when playing back with either opencv or Pylon Viewer itself. 70 frames have a size of ~7MB or 100kB per frame. Is this the best that we can get (being single thread CPU limited)? I'd think even that small amount of frames would play back quicker.

Even the test gradients (@0.3MB/s) seem to be limited to about 100fps at least on Linux. :confused: 
I think I might've gotten a bit more with the same hardware on Windows version of Pylon Viewer / API.

> @rkantos if you lower the value of `ExposureTimeAbs` you can increase the framerate.
> As the simulated camera has no real Readout-time ... the ExposureTime ... is the Frameperiod...

Yes, I have already set my ExposureTimeAbs and FrameRateAbs. 70fps with the size noted, or a bit faster with smaller frames/AOI seems to be the limit.
