### ISSUE TITLE
Is there a better way to check if camera has PRO feature BaslerCompressionBeyond

### ISSUE THREAD

**Issue by hlacikd** [basler/pypylon#739]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

I need to check if camera has BaslerCompressionBeyond, in other words if it has pro features or not, since i am using same script for basic and pro cameras. IF i plug in basic camera it will throw error, since nodemap has no ImageCompressionMode.

Currently I do it by checking if camera contains "PRO" in model name

```python
        if "PRO" in self.model and self.camera.ImageCompressionMode.Value == "BaslerCompressionBeyond":
            self.decompressor = pylon.ImageDecompressor()
            self.decompressor.SetCompressionDescriptor(self.camera.BslImageCompressionBCBDescriptor.GetAll())
            logger.info(f"Compression for {self} is enabled")
```

I believe there must be better way by somehow checking nodemap (which is not iterable in python) ...

Could you please point me to right direction. Thanks in advance.

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup & camera model(s) used

a2A1920-160ucBAS_default.pfs

### Runtime information:

```shell
root@basler-78978b9445-6fnvc:/app# python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, pypylon.pylon, platform
>>> print(f'python: {sys.version}')
python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
>>> print(f'platform: {sys.platform}/{platform.machine()}/{platform.release()}')
platform: linux/aarch64/5.10.160
>>> print(f'pypylon: {pypylon.pylon.__version__} / {".".join([str(i) for i in pypylon.pylon.GetPylonVersion()])}')
pypylon: 3.0.1 / 7.4.0.38864
>>>
```

**Comment by SMA2016a** [comment]
it may be easier if you simply check if the node is available

 if genicam.IsWritable(camera.ImageCompressionMode):
        #do something
    else:
        raise pylon.RuntimeException("The camera doesn't support BaslerCompressionBeyond features")
