### ISSUE TITLE
barcode reader issue:attribute error

### ISSUE THREAD

**Issue by Thyagutamizhan** [basler/pypylon#74]
CODE:
from pypylon import pylon
import cv2
from pyzbar.pyzbar import decode, _decode_symbols

camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateFirstDevice())

numberOfImagesToGrab = 100
camera.StartGrabbingMax(numberOfImagesToGrab)

while camera.IsGrabbing():
    grabResult = camera.RetrieveResult(5000, pylon.TimeoutHandling_ThrowException)

    if grabResult.GrabSucceeded():
        # Access the image data.
        # print("SizeX: ", grabResult.Width)
        # print("SizeY: ", grabResult.Height)
        img = grabResult.Array
        # print("Gray value of first pixel: ", img[0, 0])

    grabResult.Release()

#cv2.imshow('image',image)
image=cv2.resize(img,(0,0),fx=0.5,fy=0.5)
barcodes=decode(image)
for bar in barcodes:
    x,y,w,h=bar.rect
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)
    bardata=bar.data.decode('utf-8')
    bartype=bar.type
    print('INFO Found in Barcode:',bardata, bartype)
cv2.imshow('Image', image)
cv2.waitKey(0)

STACK TRACE:
C:\Users\Thyagu\python.exe C:/Users/Thyagu/pycharmprojects/open_cv/single_image_barcode_decode.py
Traceback (most recent call last):
[]
  File "C:/Users/Thyagu/pycharmprojects/open_cv/single_image_barcode_decode.py", line 26, in <module>
    x,y,w,h=barcodes.rect
AttributeError: 'list' object has no attribute 'rect'

Process finished with exit code 1

**Comment by thiesmoeller** [comment]
for the code you posted, it is best to use the markdown formatting for code. [ use preview to check before posting ]

For the pypylon code: 
typical loop would release the grabresult at the end of the processing.

The error you see:
this is an error coming from pyzbar. [github.com/pyzbar](https://github.com/NaturalHistoryMuseum/pyzbar)
check there what preconditions are  required for a successful decode
