### ISSUE TITLE
fail when install pypylon on raspberry pi

### ISSUE THREAD

**Issue by lytandat** [basler/pypylon#750]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

Hello, 
I am trying to install the pypylon library onto the raspberry pi, I have followed the steps as instructed but in the last step pip3 install the installation path has an error, my error is as shown in the image below, do you have a solution? Can anyone fix this error so I can install the library on my raspberry pi?
![z5416631458304_8a25a37d521105564f240b8b286789a6](https://github.com/basler/pypylon/assets/135298492/69bf2264-d2e5-40c6-8112-34a06f92c7c6)

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup & camera model(s) used

ac2500

### Runtime information:

```shell
i'm using python 3.9.2
```

**Comment by lytandat** [comment]
my RPi runs on ARMV7L

**Comment by thiesmoeller** [comment]
Have you tried installing with 

pip install pypylon

**Comment by lytandat** [comment]
thank you so much

Vào Th 3, 7 thg 5, 2024 vào lúc 13:41 Thies Möller <
***@***.***> đã viết:
