### ISSUE TITLE
No USB cameras found in python process (Pylon viewer works)

### ISSUE THREAD

**Issue by Bonitodelcapo** [basler/pypylon#773]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

I would just like to be able to connect to the camera.

This is the python file 

```
from pypylon import pylon

# List all connected devices
available_cameras = pylon.TlFactory.GetInstance().EnumerateDevices()

if not available_cameras:
    raise RuntimeError("No cameras found.")

print("Available cameras:")
for i, camera_info in enumerate(available_cameras):
    print(f"[{i}] - {camera_info.GetFriendlyName()}")

# Select the first available camera (you can modify this if you have multiple cameras)
camera = pylon.InstantCamera(pylon.TlFactory.GetInstance().CreateDevice(available_cameras[0]))

# Open the camera
camera.Open()

# Display camera model name
print("Camera opened:", camera.GetDeviceInfo().GetModelName())
```
i checked that udev rules are modified for usb cameras as described in the installation process.

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup & camera model(s) used

Camera: Basler acA4024-29uc
Pylon: 7.4.0
Pypylon: 2.3.0
OS: Ubuntu 20.04
Hardware: Jetson Orin NX 16GB
python: 3.8.10

2m USB cable directly connected (no HUB)

### Runtime information:

```shell
python: 3.8.10 (default, Jul 29 2024, 17:02:10) 
[GCC 9.4.0]
platform: linux/aarch64/5.10.104-tegra
pypylon: 2.3.0+pylon7.4.0 / 7.4.0.38864

No containerized application
```

**Comment by SMA2016a** [comment]
would you test your script with sudo?
