### ISSUE TITLE
No Devices Found in Pylon Viewer: Steps to Resolve the Issue

### ISSUE THREAD

**Issue by shimens** [basler/pypylon#786]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

I'm currently experiencing an issue where no devices are detected in the Pylon Viewer. What are the potential solutions to address this problem?

I recently acquired the a2a2840-67g5mUV camera and connected it via an Ethernet cable, but nothing appears on the Pylon Viewer or in the IP Configurator. Interestingly, I also have a SWIR camera from Basler, which is also an Ace2 series, and when I connect it with the same Ethernet cable, it works flawlessly.

Do these two cameras require different options for proper operation?

### Is your camera operational in Basler pylon viewer on your platform

No

### Hardware setup & camera model(s) used

SWIR : a2A2640 - 240gmSWIR

UV : a2A2840 - 67g5mUV

### Runtime information:

```shell
No devices found!
```

**Comment by SMA2016a** [comment]
what is your operating system? if Linux, try to start pylon viewer as sudo.
would you post the output of lsusb command

**Comment by SMA2016a** [comment]
then start pylon USB logging tool and post me the log

**Comment by SMA2016a** [comment]
Sorry, you have a GigE Camera. Can you open Ip configuration tool and check if it sees the cameras. You may be disable your firewall.

**Comment by shimens** [comment]
> Sorry, you have a GigE Camera. Can you open Ip configuration tool and check if it sees the cameras. You may be disable your firewall.

When connecting the SWIR camera, the image appears as expected. However, when connecting the UV camera, nothing shows up. Could this be a firewall issue?

![스크린샷 2024-10-15 162013](https://github.com/user-attachments/assets/7f2c0845-d7fa-4c0c-b0d5-14350a37fb1b)
![스크린샷 2024-10-15 162247](https://github.com/user-attachments/assets/90207588-eea0-44af-8b00-a344f47508fd)

**Comment by shimens** [comment]
"이더넷" means "ethernet"

**Comment by SMA2016a** [comment]
would you send me the serial number of the UV camera via private message,please

**Comment by shimens** [comment]
> would you send me the serial number of the UV camera via private message,please
> 
> does the camera gets warm if you connect the camera to network? do do power the camera via POE?

No, the camera does not get warm when connected via an Ethernet cable, and the LED does not turn on.
The SWIR camera, however, operates normally, and all these issues are occurring only with the UV camera.

Could you provide an email or other contact method so I can send the UV camera serial number privately?

**Comment by shimens** [comment]
I've just disabled the firewall and tried again, but it's still showing 'no devices found'

**Comment by venkatyash1523** [comment]
When connecting the SWIR camera, the image appears as expected. However, when connecting the UV camera, nothing shows up. Could this be a firewall issue?

**Comment by venkatyash1523** [comment]
I'm currently experiencing an issue where no devices are detected in the Pylon Viewer. What are the potential solutions to address this problem?

**Comment by venkatyash1523** [comment]
Kindly send contact details

**Comment by venkatyash1523** [comment]
3days line stop kindly solve

**Comment by SMA2016a** [comment]
https://www.baslerweb.com/de-de/support/kontakt/

**Comment by SMA2016a** [comment]
I do not find any entries or private message right now.
