### ISSUE TITLE
Re: No Devices Found in Pylon Viewer: Steps to Resolve the Issue

### ISSUE THREAD

**Issue by shimens** [basler/pypylon#787]
> would you send me the serial number of the UV camera via private message,please
> 
> does the camera gets warm if you connect the camera to network? do do power the camera via POE?

No, the camera does not get warm when connected via an Ethernet cable, and the LED does not turn on.
The SWIR camera, however, operates normally, and all these issues are occurring only with the UV camera.

Could you provide an email or other contact method so I can send the UV camera serial number privately?

_Originally posted by @shimens in https://github.com/basler/pypylon/issues/786#issuecomment-2415391721_

**Comment by SMA2016a** [comment]
let view your email address in your profile, so can send you a private message.

**Comment by shimens** [comment]
> let view your email address in your profile, so can send you a private message

I've switched my email visibility to public. Could you please check again?

**Comment by shimens** [comment]
If it isn't visible, could you kindly contact me at [elec7230@gmail.com]?

**Comment by SMA2016a** [comment]
sure

**Comment by SMA2016a** [comment]
next step in progerss

**Comment by shimens** [comment]
I’m afraid I might be misunderstanding, but could you clarify what you
mean by 'next step in progress'? As far as I’m aware, nothing has been
resolved yet.

2024년 10월 18일 (금) 오후 3:48, SMA2016a ***@***.***>님이 작성:
