### ISSUE TITLE
How to read the pixel size of a camera?

### ISSUE THREAD

**Issue by BenediktBurger** [basler/pypylon#788]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

How can I read the pixel size of a camera (e.g. 3.75 µm x 3.75µm) in order to measure the size (in physical quantities) of an image on the chip?

Thank you!

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup & camera model(s) used

daA1280-54um and daA2500-14um cameras, in our case.

### Runtime information:

```shell
not needed for the question.
```

**Comment by SMA2016a** [comment]
As I informed there is no parameter where this value can be read

**Comment by BenediktBurger** [comment]
Thanks.
