### ISSUE TITLE
Function to see which basic parameters I can change

### ISSUE THREAD

**Issue by Nemarott** [basler/pypylon#796]
### Describe what you want to implement and what the issue & the steps to reproduce it are:

I am a beginner. I watched the hour long webinar and tried searching in the C++ documentation but did not find this or maybe I just missed it. Is there a function I can call to get al parameters like Gain, Exposure Time or Pixel Format which can be adjusted?

### Is your camera operational in Basler pylon viewer on your platform

Yes

### Hardware setup used

Windows

### Camera(s) used

acA3088-57um

### Runtime information:

```shell
python: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]
platform: win32/AMD64/10
pypylon: 4.0.0 / 8.0.0.10
```

**Comment by HighImp** [comment]
Hi, please find all the functions to manipulate the camera parameter in the [Documentation](https://docs.baslerweb.com/gain#python_1), just copy the Sample Code

It's basically the same for all features, here for setting the gain value to maximum:
```python
camera.Open()
camera.Gain.Value = camera.Gain.Max
camera.Close()```
