### ISSUE TITLE
request for windows 32bit / python 3.7 binary

### ISSUE THREAD

**Issue by tiggersternchen** [basler/pypylon#81]
Could you please complile and upload the "pypylon-1.3.1-cp37-cp37m-win32.whl" version (Python 3.7, Windows x32) ?

Many thanks in advance
Sven

**Comment by Knoose** [comment]
I am also looking for this version

**Comment by Knoose** [comment]
I was able to build it myself. I tried to use the feature/python37 branch but that failed pretty miserably. If you need me to share it, I can but ideally Basler should release a working binary.

**Comment by tiggersternchen** [comment]
I would be greatful if you could share your compiled version until Basler releases an official build.

Thanks in advance
Sven

**Comment by stefanklug** [comment]
Hi,
I just tagged a 1.4.0 release candidate. The wheel is here:
https://github.com/basler/pypylon/releases/download/1.4.0rc1/pypylon-1.4.0rc1-cp37-cp37m-win32.whl
Feel free to test it.

**Comment by tiggersternchen** [comment]
Thank you for your effort Stefan,

it's working for our USB3 camera. Unfortunately we have recognized that the pypylon wrapper does not support 1394 firewire cameras. Do you or somebody else know a workaround ?

Thank you very much
Sven

**Comment by Knoose** [comment]
Have you looked that this? https://github.com/basler/pypylon/issues/47

**Comment by thiesmoeller** [comment]
original issue is fixed
