### ISSUE TITLE
issue working with UserOutputValueAll feature

### ISSUE THREAD

**Issue by Thyagutamizhan** [basler/pypylon#89]
Hi, actually i accessed the UserOutputValueAll  feature of basler acA640-750mc camera. I set it on with some conditions it perfectly works. But its continuosly in on condition, i have tried to off r disable it but the output is flowing continuously even if i switch off the camera. how can i resole it?

**Comment by thiesmoeller** [comment]
This model doesn't exist.

Thiyagarajan <notifications@github.com> schrieb am Do., 28. Feb. 2019,
06:40:

**Comment by Thyagutamizhan** [comment]
Is there any solutions to get rid of the issue . 
model: acA640-750uc

**Comment by thiesmoeller** [comment]
What output lines are you using?
GPIO or opto coupled ?

Example circuits, that you should follow to design your output circuit are in [docs io](https://docs.baslerweb.com/#t=en%2Fcircuit_diagrams_(ace).htm)
And please select your model in the doc system. It will select the right detail docu sections.

**Comment by thiesmoeller** [comment]
no feedback by user for 1.5 years
