### ISSUE TITLE
How to run a c++ sample code in python

### ISSUE THREAD

**Issue by zamarjavier** [basler/pypylon#92]
Hello,

I'm new using basler cameras. I'm trying to take photos with a usb camera using pylon5 and executed from python. 
The idea is to run the c++ code to take a photo (from python), store the photo in a python variable and then use this variable in python to  process it. How can I do it?

I thought in use a tcp conexion between c++ code and python code, but maybe the process to follow is easier.

Can anyone help me?

Thank you so much.

**Comment by thiesmoeller** [comment]
Hi @zamarjavier,

this is the python binding to basler cameras. You can do the same things you can do using the C++ APIs.

Look into the samples folder to get an idea, of what is possible.

Or is there a strict reason for you to use C++ _and_ python?

**Comment by spy14414** [comment]
You can wrap c++ ​​code into a dynamic link library.Then  you just need to call this dll in python.

**Comment by thiesmoeller** [comment]
off topic issue, as this is the python binding.
