### ISSUE TITLE
How to capture images with different exposures?

### ISSUE THREAD

**Issue by chuong** [basler/pypylon#94]
I would like to capture an HDR image by combining images of different exposures. How such images can be captured efficiently using Pypylon?

Thanks

**Comment by chuong** [comment]
This is similar to Sequencer feature available in C/C++ interface:
https://docs.baslerweb.com/#t=en%2Fsequencer_(gige_cameras).htm

How can this be done in Python?

**Comment by thiesmoeller** [comment]
[See in this issue](https://github.com/basler/pypylon/issues/67#issuecomment-457585961)

**Comment by chuong** [comment]
Great pointer. Thanks @thiesmoeller.

**Comment by chuong** [comment]
Hi @thiesmoeller, the python example you mentioned is for USB3 camera and it doesn't work for my GigE Blasler camera.

I tried to translate C++ code from https://docs.baslerweb.com/#t=en%2Fsequencer_(gige_cameras).htm to python but there are missing python functions.

**Comment by thiesmoeller** [comment]
@chuong as all features are downloaded from the camera itself, in principle there can't be a missing function
