### ISSUE TITLE
PixelType_BayerGB12packed?

### ISSUE THREAD

**Issue by nikkadim** [basler/pypylon#98]
Any ways to to set "Bayer GB 12 Packed" pixel format?  (piA1600-35)

Thank you.

**Comment by thiesmoeller** [comment]
in your code you can call:

`print(cam.PixelFormat.Symbolics)`

to output all available Pixelformat.
The pilot piA1600-35 should support "BayerGB12Packed" ....

**Comment by zimmerm** [comment]
In case you wonder why the list of formats you get is empty. The camera needs to be opened so you can read these attributes.
